### ISSUE TITLE
Unit / functional / integration testing of renderd

### ISSUE THREAD

**Issue by apmon** [openstreetmap/mod_tile#10]
Currently mod_tile and renderd don't have a regression test suit. It is therefore unfortunately too easy to break something without noticing.

To try and continue to improve the quality of the software, it would be good to have a unit / functional / integration test suit.

This issue can be used to discuss the initial creation of such a test suit and how best to go about it.

**Comment by xamanu** [comment]
This has been merged. Tests can always be improved and extended but at least we have a basic framework up and running.
