### ISSUE TITLE
segfault from mapnik when rendering

### ISSUE THREAD

**Issue by coreysdickson** [openstreetmap/mod_tile#101]
renderd[1751]: Using plate carree projection settings
renderd[1751]: DEBUG: Got incoming connection, fd 5, number 1
renderd[1751]: DEBUG: Got incoming request with protocol version 2
renderd[1751]: DEBUG: Got command RenderBulk fd(5) xml(default), z(14), x(0), y(2192), mime(image/png), options()
renderd[1751]: DEBUG: START TILE default 14 0-7 2192-2199, new metatile
renderd[1751]: Rendering projected coordinates 14 0 2192 -> -20037508.342800|7328170.775760 -20027724.403179|7337954.715381 to a 8 x 8 tile

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffd3fff700 (LWP 1759)]
0x00007ffff7a39e47 in agg::pattern_filter_bilinear_rgba<agg::rgba8>::pixel_high_res(agg::rgba8 const* const*, agg::rgba8*, int, int) () from /usr/lib/libmapnik.so.2.2

Levels 0-13 render fine, it's only level 14-16 I run into problems.

**Comment by springmeyer** [comment]
@coreysdickson - hard to know the exact problem. But I've fixed what might be the same crash in Mapnik 3.x: https://github.com/mapnik/mapnik/issues/2726. So if you upgrade to mapnik 3.x rc2 and build with https://github.com/openstreetmap/mod_tile/pull/103 this crash may be gone.

**Comment by coreysdickson** [comment]
@springmeyer Upgrading mapnik to 3.x rc2 resolved the described issues in the original post.
Thanks for the assistance.
