### ISSUE TITLE
No tiles generated

### ISSUE THREAD

**Issue by damanbatra** [openstreetmap/mod_tile#105]
HI, I followed http://switch2osm.org/serving-tiles/manually-building-a-tile-server-14-04/ to roll out my pc as a mapserver. When I give the renderd command, it just halts at using webmercator projection settings and no tiles are generated on localhost/osm_tiles/0/0/0.png. Even the mod_tile folder is empty. I checked the apache error log and I get :

In the apache error.log file, I get core dump error :
[core:error] [pid 1688:tid 140121667135360] AH00546: no record of
generation 0 of exiting child 22589
[Thu Jul 09 18:29:53.015305 2015] [core:notice] [pid 1688:tid
140121667135360] AH00051: child pid 22590 exit signal Segmentation
fault (11), possible coredump in /etc/apache2

Please suggest something so as to make it work!

**Comment by openstreetmap-tiles** [comment]
First obvious question: Did you import a planet file yet?

Lynn (D)

**Comment by DamBatra** [comment]
On 21 Jul 2015 00:35, "OpenStreetMap Tile Serving" <notifications@github.com>
wrote:
>
> First obvious question: Did you import a planet file yet?
>
> Lynn (D)

I imported the osm data of my area, not the entire planet and the world
boundaries and coastlines like shape files.

**Comment by palassonde** [comment]
I would suggest restarting apache and renderd, repeat the command and then take a look at the syslog file. It is under /var/log/syslog. That should give you an insight of what is happening ;)
