### ISSUE TITLE
Compile error OS X

### ISSUE THREAD

**Issue by alenkas** [openstreetmap/mod_tile#106]
Trying to build tile server ([instructions](https://switch2osm.org/serving-tiles/manually-building-a-tile-server-12-04/)), no luck ([more details](http://stackoverflow.com/questions/31729036/render-or-not-to-render-building-a-tile-server)). Seems that mod_tile installation was unsuccessful.

I tried [this](https://github.com/openstreetmap/mod_tile) mod_tile. But got error in the end: [logs](https://gist.github.com/narcissic/6f2c323d37d870c16c17).

Then I tried [this](https://github.com/springmeyer/mod_tile) one. It looks like it installed (only some warnings without errors), but not sure. [Logs](https://gist.github.com/narcissic/69ac6a451ce3cd7da055).

I'm new to this stuff and don't know what this errors are about. What could be the problem?

I have:
**OS**: Mac Os X 10.9.4
**Python**: 2.7.5
**Mapnik**: 3.0.1-pre
**Server version**: Apache/2.2.26 (Unix)

**Comment by pnorman** [comment]
https://gist.github.com/narcissic/6f2c323d37d870c16c17 is not found. Please attach the errors.

**Comment by alenkas** [comment]
Oops, sorry, my fault
The first one https://gist.github.com/alenkas/6f2c323d37d870c16c17
The second 
https://gist.github.com/alenkas/69ac6a451ce3cd7da055

**Comment by jburgess777** [comment]
The errors on one of the links are about:
```
./src/mod_tile.c:756:19: error: no member named 's6_addr32' in 'struct in6_addr'
    hashkey = (ip.s6_addr32[0] ^ ip.s6_addr32[1] ^ ip.s6_addr32[2] ^ ip.s6_addr32[3]) % DELAY_HASHTABLE_SIZE;
```
This is due to 8307d19a which relaced the s6_addr with s6_addr32. Unfortunately this isn't supported on OSX. This has caught other people out too, e.g. http://seclists.org/nmap-dev/2009/q1/493

It is fixable by reverting that single line of code change but I'm not entirely happy with those casts between uint8_t* and uint32_t*.

**Comment by inferiorhumanorgans** [comment]
8307d19 also breaks compilation on FreeBSD

**Comment by xamanu** [comment]
Closing here. I don't think support for OSX is our scope here. Sorry.
