### ISSUE TITLE
increase MAX_ZOOM limit for tiles rendering

### ISSUE THREAD

**Issue by puntonero** [openstreetmap/mod_tile#112]
Hi,
in last version of mod_tile I can't find the right way to increase MAX_ZOOM to 22 instead of 18.
In the past (may be 6 months ago) was simple like change the value in render_config.h.

Any help will be appreciated.
Thank in advance

P.S.
of course I've already searched for occurrences of MAX_ZOOM, maxzoom and maxZoom and set value to 22 but tiles rendering is still locked to 18

**Comment by yvecai** [comment]
It's an option in renderd.conf.

**Comment by SomeoneElseOSM** [comment]
(somewhat offtopic, because it's not a bug, but) it actually needs changing in up to 3 places, as described here:

http://wiki.openstreetmap.org/wiki/User:SomeoneElse/Tileserver_zoom_levels
