### ISSUE TITLE
Renderd not rendering 

### ISSUE THREAD

**Issue by psinghsp** [openstreetmap/mod_tile#113]
We built a brand new openstreet map server using instructions here:
https://switch2osm.org/serving-tiles/manually-building-a-tile-server-14-04/

We used Ubuntu 14.04, 8GB RAM, 1.5TB SSD drives in AWS.

The test works fine:
http://yourserveraddress/osm_tiles/0/0/0.png

But when I use "leaflet" and it starts issuing commands like:
http://server/osm_tiles/9/256/170.png

I see these errors in the syslog:
Oct 21 05:39:47 ip-10-200-1-158 renderd[1339]: DEBUG: Got incoming connection, fd 8, number 1
Oct 21 05:39:47 ip-10-200-1-158 renderd[1339]: DEBUG: Got incoming request with protocol version 2
Oct 21 05:39:47 ip-10-200-1-158 renderd[1339]: DEBUG: Got command RenderPrio fd(8) xml(default), z(9), x(256), y(170), mime(image/png), options()
Oct 21 05:40:01 ip-10-200-1-158 CRON[21630]: (root) CMD (if [ -x /etc/munin/plugins/apt_all ]; then munin-run apt_all update 7200 12 >/dev/null; elif [ -x /etc/munin/plugins/apt ]; then munin-run apt update 7200 12 >/dev/null; fi)
Oct 21 05:40:01 ip-10-200-1-158 CRON[21631]: (munin) CMD (if [ -x /usr/bin/munin-cron ]; then /usr/bin/munin-cron; fi)
Oct 21 05:40:17 ip-10-200-1-158 renderd[1339]: DEBUG: Failed to read cmd on fd 8
Oct 21 05:40:17 ip-10-200-1-158 renderd[1339]: DEBUG: Connection 0, fd 8 closed, now 0 left
Oct 21 05:45:01 ip-10-200-1-158 CRON[21933]: (root) CMD (if [ -x /etc/munin/plugins/apt_all ]; then munin-run apt_all update 7200 12 >/dev/null; elif [ -x /etc/munin/plugins/apt ]; then munin-run apt update 7200 12 >/dev/null; fi)
Oct 21 05:45:01 ip-10-200-1-158 CRON[21934]: (munin) CMD (if [ -x /usr/bin/munin-cron ]; then /usr/bin/munin-cron; fi)

Is this a known problem? I got latest pbf and latest software last week.

**Comment by psinghsp** [comment]
If you fetch a tile for the very first time, the error is slightly different:

Oct 21 05:49:03 ip-10-200-1-158 renderd[1339]: DEBUG: Got incoming connection, fd 8, number 1
Oct 21 05:49:03 ip-10-200-1-158 renderd[1339]: DEBUG: Got incoming request with protocol version 2
Oct 21 05:49:03 ip-10-200-1-158 renderd[1339]: DEBUG: Got command RenderPrio fd(8) xml(default), z(2), x(0), y(1), mime(image/png), options()
Oct 21 05:49:03 ip-10-200-1-158 renderd[1339]: DEBUG: START TILE default 2 0-3 0-3, new metatile
Oct 21 05:49:03 ip-10-200-1-158 renderd[1339]: Rendering projected coordinates 2 0 0 -> -20037508.342800|-20037508.342800 20037508.342800|20037508.342800 to a 4 x 4 tile
Oct 21 05:49:33 ip-10-200-1-158 renderd[1339]: DEBUG: Failed to read cmd on fd 8
Oct 21 05:49:33 ip-10-200-1-158 renderd[1339]: DEBUG: Connection 0, fd 8 closed, now 0 left

**Comment by psinghsp** [comment]
We even resized the AWS instance to have 16 GB of RAM and 8 CPUs. But tiles just don't get rendered for any zoom levels other than 1 and 2. The requests just time out. What are the trouble shooting steps do I need to take to resolve this?

**Comment by woodpeck** [comment]
Suggest taking this to a suitable mailing list (eg https://lists.openstreetmap.org/listinfo/tile-serving) - this is a place for discussing issues with mod_tile, not issues with one particular setup. Are you sure your renderd processes are not crashing (anything about segfaults visible in dmesg output)? is the metatile actually created (just not delivered) or is it never created at all? Are metatiles created if you run render_list?

**Comment by psinghsp** [comment]
Tiles seem to be there for zoom level 1 and 2. Thanks for the pointer. I will move this to the mailing list.

Renderd is not crashing. I checked the logs.

**Comment by ReckyXXX** [comment]
Hi! I have the similar problem today. Try to change your leaflet code to 
map = new L.Map('map');
//var osmUrl='http://{s}.localhost/osm_tiles/{z}/{x}/{y}.png';
// Without {s}:
var osmUrl='http://localhost/osm_tiles/{z}/{x}/{y}.png';
var osmAttrib=' ';
var osm = new L.TileLayer(osmUrl, {minZoom: 8, maxZoom: 17, attribution: osmAttrib});
map.addLayer(osm);

**Comment by tierpod** [comment]
I have the same problem. Some tiles do not rendering:
```
ноя 20 10:37:32 tileserver renderd[21001]: DEBUG: START TILE default 7 72-79 32-39, new metatile
ноя 20 10:37:32 tileserver renderd[21001]: Rendering projected coordinates 7 72 32 -> 2504688.542850|7514065.628550 5009377.085700|10018754.171400 to a 8 x 8 tile
ноя 20 10:37:32 tileserver renderd[21001]: DEBUG: Got incoming connection, fd 9, number 2
ноя 20 10:37:32 tileserver renderd[21001]: DEBUG: Got incoming connection, fd 10, number 3
ноя 20 10:37:32 tileserver renderd[21001]: DEBUG: Got incoming request with protocol version 2
ноя 20 10:37:32 tileserver renderd[21001]: DEBUG: Got command RenderPrio fd(9) xml(default), z(7), x(74), y(39), mime(image/png), options()
ноя 20 10:37:32 tileserver renderd[21001]: DEBUG: Got incoming request with protocol version 2
ноя 20 10:37:32 tileserver renderd[21001]: DEBUG: Got command RenderPrio fd(10) xml(default), z(7), x(75), y(39), mime(image/png), options()
ноя 20 10:37:32 tileserver renderd[21001]: DEBUG: Got incoming connection, fd 11, number 4
ноя 20 10:37:32 tileserver renderd[21001]: DEBUG: Got incoming connection, fd 12, number 5
ноя 20 10:37:32 tileserver renderd[21001]: DEBUG: Got incoming request with protocol version 2
ноя 20 10:37:32 tileserver renderd[21001]: DEBUG: Got command RenderPrio fd(11) xml(default), z(7), x(77), y(39), mime(image/png), options()
ноя 20 10:37:32 tileserver renderd[21001]: DEBUG: Got incoming request with protocol version 2
ноя 20 10:37:32 tileserver renderd[21001]: DEBUG: Got command RenderPrio fd(12) xml(default), z(7), x(76), y(39), mime(image/png), options()
ноя 20 10:37:33 tileserver renderd[21001]: DEBUG: Got incoming connection, fd 13, number 6
ноя 20 10:37:33 tileserver renderd[21001]: DEBUG: Got incoming request with protocol version 2
ноя 20 10:37:33 tileserver renderd[21001]: DEBUG: Got command RenderPrio fd(13) xml(default), z(7), x(79), y(39), mime(image/png), options()
ноя 20 10:37:42 tileserver renderd[21001]: DEBUG: Failed to read cmd on fd 7
ноя 20 10:37:42 tileserver renderd[21001]: DEBUG: Connection 0, fd 7 closed, now 5 left
ноя 20 10:37:42 tileserver renderd[21001]: DEBUG: Got incoming connection, fd 7, number 6
ноя 20 10:37:42 tileserver renderd[21001]: DEBUG: Got incoming request with protocol version 2
ноя 20 10:37:42 tileserver renderd[21001]: DEBUG: Got command RenderPrio fd(7) xml(default), z(7), x(78), y(39), mime(image/png), options()
ноя 20 10:37:42 tileserver renderd[21001]: DEBUG: Failed to read cmd on fd 9
ноя 20 10:37:42 tileserver renderd[21001]: DEBUG: Connection 0, fd 9 closed, now 5 left
ноя 20 10:37:42 tileserver renderd[21001]: DEBUG: Failed to read cmd on fd 10
ноя 20 10:37:42 tileserver renderd[21001]: DEBUG: Connection 0, fd 10 closed, now 4 left
ноя 20 10:37:42 tileserver renderd[21001]: DEBUG: Failed to read cmd on fd 11
ноя 20 10:37:42 tileserver renderd[21001]: DEBUG: Connection 0, fd 11 closed, now 3 left
ноя 20 10:37:42 tileserver renderd[21001]: DEBUG: Failed to read cmd on fd 12
ноя 20 10:37:42 tileserver renderd[21001]: DEBUG: Connection 0, fd 12 closed, now 2 left
ноя 20 10:37:43 tileserver renderd[21001]: DEBUG: Failed to read cmd on fd 13
ноя 20 10:37:43 tileserver renderd[21001]: DEBUG: Connection 0, fd 13 closed, now 1 left
ноя 20 10:37:50 tileserver renderd[21001]: DEBUG: DONE TILE default 7 72-79 32-39 in 17.637 seconds
```
But mos of tiles renreding fine. I think, problem with some timeout settings.

**Comment by gravitystorm** [comment]
> I have the same problem. Some tiles do not rendering:

No, you have a different problem!

> ноя 20 10:37:50 tileserver renderd[21001]: DEBUG: DONE TILE default 7 72-79 32-39 in 17.637 seconds

Your tile rendered fine, it just took 17 seconds. Mod_tile by default only waits 10 seconds though before giving up.

https://github.com/openstreetmap/mod_tile/blob/6b9611aaf763f4f776d1fd363433aac7e25cb34b/mod_tile.conf#L44

You probably want to change how long it waits for missing tiles to a higher value.

Thanks,
Andy

**Comment by tierpod** [comment]
Thank you, it helped to me.

**Comment by kanishkamehta-Aricent** [comment]
In the logs, I am getting as : 

DEBUG: START TILE ajt 5 16-23 8-15, new metatile
DEBUG: DONE TILE ajt 5 16-23 8-15 in 7.528 seconds

But tiles are not loading on the browser. I am not able to rectify the issue.

**Comment by SomeoneElseOSM** [comment]
@kanishkamehta-Aricent You'll need to provide more information that that, I'm afraid, and a github issue from 2015 isn't the best place to ask.  I'd suggest asking a question at help.openstreetmap.org, and giving details of the browser URLs that you are using to try and access your tiles.
