### ISSUE TITLE
Renderd stucks on: renderd[5163]: Using web mercator projection settings

### ISSUE THREAD

**Issue by Amrizhan** [openstreetmap/mod_tile#115]
Hi everybody, it is last step
I got my data on Postgis imported by osm2pgsql, configure renderd.conf and mod_tile.conf as described on tutorials. When I run renderd -f -c /usr/local/etc/renderd.conf it stuck on: Using web mercator projection settings

```
root@osm-VirtualBox:/home/osm# renderd -f -c /usr/local/etc/renderd.conf
renderd[5163]: Rendering daemon started
renderd[5163]: Initiating reqyest_queue
iniparser: syntax error in /usr/local/etc/renderd.conf (7):
-> ;[renderd01]
iniparser: syntax error in /usr/local/etc/renderd.conf (14):
-> ;[renderd02]
iniparser: syntax error in /usr/local/etc/renderd.conf (33):
-> ;** config options used by mod_tile, but not renderd **
iniparser: syntax error in /usr/local/etc/renderd.conf (45):
-> ;[style2]
iniparser: syntax error in /usr/local/etc/renderd.conf (52):
-> ;** config options used by mod_tile, but not renderd **
renderd[5163]: Parsing section renderd
renderd[5163]: Parsing render section 0
renderd[5163]: Parsing section mapnik
renderd[5163]: Parsing section default
renderd[5163]: config renderd: unix socketname=/var/run/renderd/renderd.sock
renderd[5163]: config renderd: num_threads=4
renderd[5163]: config renderd: num_slaves=0
renderd[5163]: config renderd: tile_dir=/var/lib/mod_tile
renderd[5163]: config renderd: stats_file=/var/run/renderd/renderd.stats
renderd[5163]: config mapnik:  plugins_dir=/usr/local/lib/mapnik/input
renderd[5163]: config mapnik:  font_dir=/usr/share/fonts/truetype/ttf-dejavu
renderd[5163]: config mapnik:  font_dir_recurse=1
renderd[5163]: config renderd(0): Active
renderd[5163]: config renderd(0): unix socketname=/var/run/renderd/renderd.sock
renderd[5163]: config renderd(0): num_threads=4
renderd[5163]: config renderd(0): tile_dir=/var/lib/mod_tile
renderd[5163]: config renderd(0): stats_file=/var/run/renderd/renderd.stats
renderd[5163]: config map 0:   name(default) file(/usr/local/share/maps/style/OSMBright/OSMBright.xml) uri(/osm_tiles/) htcp() host(localhost)
renderd[5163]: Initialising unix server socket on /var/run/renderd/renderd.sock
renderd[5163]: Created server socket 4
renderd[5163]: Renderd is using mapnik version 2.2.0
renderd[5163]: DEBUG: Loading font: /usr/share/fonts/truetype/ttf-dejavu/DejaVuSansCondensed.ttf
renderd[5163]: DEBUG: Loading font: /usr/share/fonts/truetype/ttf-dejavu/DejaVuSerifCondensed-BoldItalic.ttf
renderd[5163]: DEBUG: Loading font: /usr/share/fonts/truetype/ttf-dejavu/DejaVuSansMono-Oblique.ttf
renderd[5163]: DEBUG: Loading font: /usr/share/fonts/truetype/ttf-dejavu/DejaVuSerif-Italic.ttf
renderd[5163]: DEBUG: Loading font: /usr/share/fonts/truetype/ttf-dejavu/DejaVuSans-Bold.ttf
renderd[5163]: DEBUG: Loading font: /usr/share/fonts/truetype/ttf-dejavu/DejaVuSansCondensed-Bold.ttf
renderd[5163]: DEBUG: Loading font: /usr/share/fonts/truetype/ttf-dejavu/DejaVuSerifCondensed.ttf
renderd[5163]: DEBUG: Loading font: /usr/share/fonts/truetype/ttf-dejavu/DejaVuSerif.ttf
renderd[5163]: DEBUG: Loading font: /usr/share/fonts/truetype/ttf-dejavu/DejaVuSans-BoldOblique.ttf
renderd[5163]: DEBUG: Loading font: /usr/share/fonts/truetype/ttf-dejavu/DejaVuSerif-BoldItalic.ttf
renderd[5163]: DEBUG: Loading font: /usr/share/fonts/truetype/ttf-dejavu/DejaVuSerif-Bold.ttf
renderd[5163]: DEBUG: Loading font: /usr/share/fonts/truetype/ttf-dejavu/DejaVuSerifCondensed-Bold.ttf
renderd[5163]: DEBUG: Loading font: /usr/share/fonts/truetype/ttf-dejavu/DejaVuSansCondensed-Oblique.ttf
renderd[5163]: DEBUG: Loading font: /usr/share/fonts/truetype/ttf-dejavu/DejaVuSansMono-Bold.ttf
renderd[5163]: DEBUG: Loading font: /usr/share/fonts/truetype/ttf-dejavu/DejaVuSansMono.ttf
renderd[5163]: DEBUG: Loading font: /usr/share/fonts/truetype/ttf-dejavu/DejaVuSansCondensed-BoldOblique.ttf
renderd[5163]: DEBUG: Loading font: /usr/share/fonts/truetype/ttf-dejavu/DejaVuSans-ExtraLight.ttf
renderd[5163]: DEBUG: Loading font: /usr/share/fonts/truetype/ttf-dejavu/DejaVuSerifCondensed-Italic.ttf
renderd[5163]: DEBUG: Loading font: /usr/share/fonts/truetype/ttf-dejavu/DejaVuSans.ttf
renderd[5163]: DEBUG: Loading font: /usr/share/fonts/truetype/ttf-dejavu/DejaVuSans-Oblique.ttf
renderd[5163]: DEBUG: Loading font: /usr/share/fonts/truetype/ttf-dejavu/DejaVuSansMono-BoldOblique.ttf
Running in foreground mode...
debug: init_storage_backend: initialising file storage backend at: /var/lib/mod_tile
renderd[5163]: Loading parameterization function for 
debug: init_storage_backend: initialising file storage backend at: /var/lib/mod_tile
renderd[5163]: Loading parameterization function for 
debug: init_storage_backend: initialising file storage backend at: /var/lib/mod_tile
renderd[5163]: Loading parameterization function for 
debug: init_storage_backend: initialising file storage backend at: /var/lib/mod_tile
renderd[5163]: Loading parameterization function for 
renderd[5163]: Starting stats thread
renderd[5163]: Using web mercator projection settings
renderd[5163]: Using web mercator projection settingsrenderd[5163]: Using web mercator projection settings

```

Help me!!!

This is my renderd.conf file

```
[renderd]
socketname=/var/run/renderd/renderd.sock
num_threads=4
tile_dir=/var/lib/mod_tile
stats_file=/var/run/renderd/renderd.stats

[mapnik]
plugins_dir=/usr/local/lib/mapnik/input
font_dir=/usr/share/fonts/truetype/ttf-dejavu
font_dir_recurse=1

[default]
URI=/osm_tiles/
TILEDIR=/var/lib/mod_tile
XML=/usr/local/share/maps/style/OSMBright/OSMBright.xml
HOST=localhost
TILESIZE=256
```

**Comment by avirupd-egnaroinc** [comment]
I have also faced the same problem. Did not get any help from google. If anyone knows the solution please share.

Thanks in advance

**Comment by woodpeck** [comment]
Please explain the nature of the problem.

**Comment by avirupd-egnaroinc** [comment]
Hi Frederik Ramm,

    I have followed this link to generate a offline tile server
https://switch2osm.org/serving-tiles/manually-building-a-tile-server-14-04/
but after completion all the instruction I am getting pink tiles in my
offline map i.e., slippymap.html. Ans in terminal I am getting the
this "renderd[5248]:
Using web mercator projection settings
" and its not proceeding from there.


This is actual scenario-
egnaro@ubuntu:/run/renderd$ sudo -u egnaro renderd -f -c
/usr/local/etc/renderd.conf
renderd[5248]: Rendering daemon started
renderd[5248]: Initiating reqyest_queue
renderd[5248]: Parsing section renderd
renderd[5248]: Parsing render section 0
renderd[5248]: Parsing section renderd01
renderd[5248]: Parsing render section 1
renderd[5248]: Parsing section renderd02
renderd[5248]: Parsing render section 2
renderd[5248]: Parsing section mapnik
renderd[5248]: Parsing section default
renderd[5248]: Parsing section style2
renderd[5248]: config renderd: unix socketname=/var/run/renderd/renderd.sock
renderd[5248]: config renderd: num_threads=4
renderd[5248]: config renderd: num_slaves=8
renderd[5248]: config renderd: tile_dir=/var/lib/mod_tile
renderd[5248]: config renderd: stats_file=/var/run/renderd/renderd.stats
renderd[5248]: config mapnik:  plugins_dir=/usr/local/lib/mapnik/input
renderd[5248]: config mapnik:  font_dir=/usr/share/fonts/truetype/ttf-dejavu
renderd[5248]: config mapnik:  font_dir_recurse=1
renderd[5248]: config renderd(0): Active
renderd[5248]: config renderd(0): unix
socketname=/var/run/renderd/renderd.sock
renderd[5248]: config renderd(0): num_threads=4
renderd[5248]: config renderd(0): tile_dir=/var/lib/mod_tile
renderd[5248]: config renderd(0): stats_file=/var/run/renderd/renderd.stats
renderd[5248]: config renderd(1): unix
socketname=/var/run/renderd/renderd.sock
renderd[5248]: config renderd(1): num_threads=4
renderd[5248]: config renderd(1): tile_dir=/var/lib/mod_tile
renderd[5248]: config renderd(1): stats_file=(null)
renderd[5248]: config renderd(2): unix
socketname=/var/run/renderd/renderd.sock
renderd[5248]: config renderd(2): num_threads=4
renderd[5248]: config renderd(2): tile_dir=/var/lib/mod_tile
renderd[5248]: config renderd(2): stats_file=(null)
renderd[5248]: config map 0:   name(default)
file(/usr/local/share/maps/style/OSMBright/OSMBright.xml) uri(/osm_tiles/)
htcp() host(localhost)
renderd[5248]: config map 1:   name(style2) file() uri() htcp() host()
renderd[5248]: Initialising unix server socket on
/var/run/renderd/renderd.sock
renderd[5248]: Created server socket 4
renderd[5248]: Renderd is using mapnik version 2.2.0
renderd[5248]: DEBUG: Loading font:
/usr/share/fonts/truetype/ttf-dejavu/DejaVuSerifCondensed-Bold.ttf
renderd[5248]: DEBUG: Loading font:
/usr/share/fonts/truetype/ttf-dejavu/DejaVuSansMono-Oblique.ttf
renderd[5248]: DEBUG: Loading font:
/usr/share/fonts/truetype/ttf-dejavu/DejaVuSerif.ttf
renderd[5248]: DEBUG: Loading font:
/usr/share/fonts/truetype/ttf-dejavu/DejaVuSansCondensed-Oblique.ttf
renderd[5248]: DEBUG: Loading font:
/usr/share/fonts/truetype/ttf-dejavu/DejaVuSansCondensed-Bold.ttf
renderd[5248]: DEBUG: Loading font:
/usr/share/fonts/truetype/ttf-dejavu/DejaVuSerifCondensed.ttf
renderd[5248]: DEBUG: Loading font:
/usr/share/fonts/truetype/ttf-dejavu/DejaVuSansCondensed.ttf
renderd[5248]: DEBUG: Loading font:
/usr/share/fonts/truetype/ttf-dejavu/DejaVuSerif-Italic.ttf
renderd[5248]: DEBUG: Loading font:
/usr/share/fonts/truetype/ttf-dejavu/DejaVuSerifCondensed-BoldItalic.ttf
renderd[5248]: DEBUG: Loading font:
/usr/share/fonts/truetype/ttf-dejavu/DejaVuSans.ttf
renderd[5248]: DEBUG: Loading font:
/usr/share/fonts/truetype/ttf-dejavu/DejaVuSansCondensed-BoldOblique.ttf
renderd[5248]: DEBUG: Loading font:
/usr/share/fonts/truetype/ttf-dejavu/DejaVuSans-BoldOblique.ttf
renderd[5248]: DEBUG: Loading font:
/usr/share/fonts/truetype/ttf-dejavu/DejaVuSans-ExtraLight.ttf
renderd[5248]: DEBUG: Loading font:
/usr/share/fonts/truetype/ttf-dejavu/DejaVuSans-Oblique.ttf
renderd[5248]: DEBUG: Loading font:
/usr/share/fonts/truetype/ttf-dejavu/DejaVuSans-Bold.ttf
renderd[5248]: DEBUG: Loading font:
/usr/share/fonts/truetype/ttf-dejavu/DejaVuSansMono-Bold.ttf
renderd[5248]: DEBUG: Loading font:
/usr/share/fonts/truetype/ttf-dejavu/DejaVuSerif-Bold.ttf
renderd[5248]: DEBUG: Loading font:
/usr/share/fonts/truetype/ttf-dejavu/DejaVuSerif-BoldItalic.ttf
renderd[5248]: DEBUG: Loading font:
/usr/share/fonts/truetype/ttf-dejavu/DejaVuSansMono-BoldOblique.ttf
renderd[5248]: DEBUG: Loading font:
/usr/share/fonts/truetype/ttf-dejavu/DejaVuSerifCondensed-Italic.ttf
renderd[5248]: DEBUG: Loading font:
/usr/share/fonts/truetype/ttf-dejavu/DejaVuSansMono.ttf
Running in foreground mode...
debug: init_storage_backend: initialising file storage backend at:
/var/lib/mod_tile
renderd[5248]: Starting stats thread
debug: init_storage_backend: initialising file storage backend at:
/var/lib/mod_tile
renderd[5248]: Initialising unix client socket on
/var/run/renderd/renderd.sock
renderd[5248]: socket /var/run/renderd/renderd.sock initialised to fd 5
renderd[5248]: Initialising unix client socket on
/var/run/renderd/renderd.sock
renderd[5248]: Loading parameterization function for
renderd[5248]: socket /var/run/renderd/renderd.sock initialised to fd 6
debug: init_storage_backend: initialising file storage backend at:
/var/lib/mod_tile
renderd[5248]: Loading parameterization function for
renderd[5248]: Initialising unix client socket on
/var/run/renderd/renderd.sock
renderd[5248]: socket /var/run/renderd/renderd.sock initialised to fd 7
renderd[5248]: Initialising unix client socket on
/var/run/renderd/renderd.sock
debug: init_storage_backend: initialising file storage backend at:
/var/lib/mod_tile
renderd[5248]: socket /var/run/renderd/renderd.sock initialised to fd 8
renderd[5248]: Loading parameterization function for
renderd[5248]: Initialising unix client socket on
/var/run/renderd/renderd.sock
renderd[5248]: Loading parameterization function for
renderd[5248]: socket /var/run/renderd/renderd.sock initialised to fd 9
renderd[5248]: Initialising unix client socket on
/var/run/renderd/renderd.sock
renderd[5248]: Initialising unix client socket on
/var/run/renderd/renderd.sock
renderd[5248]: DEBUG: Got incoming connection, fd 12, number 1
renderd[5248]: socket /var/run/renderd/renderd.sock initialised to fd 13
renderd[5248]: socket /var/run/renderd/renderd.sock initialised to fd
14renderd[5248]: DEBUG: Got incoming connection, fd 15, number 2

renderd[5248]: DEBUG: Got incoming connection, fd 16, number 3
renderd[5248]: Initialising unix client socket on
/var/run/renderd/renderd.sockrenderd[5248]: DEBUG: Got incoming connection,
fd 17, number 4

renderd[5248]: DEBUG: Got incoming connection, fd 18, number 5
renderd[5248]: socket /var/run/renderd/renderd.sock initialised to fd 19
renderd[5248]: DEBUG: Got incoming connection, fd 20, number 6
renderd[5248]: DEBUG: Got incoming connection, fd 21, number 7
renderd[5248]: DEBUG: Got incoming connection, fd 22, number 8
renderd[5248]: Using web mercator projection settings
renderd[5248]: Using web mercator projection settings
renderd[5248]: Using web mercator projection settings
renderd[5248]: Using web mercator projection settings

Any help would be appreciated.

Thanks

**Comment by Amrizhan** [comment]
Hi guys
This means that you have done everything succesfully=)

leave that window open and try to load map on your host and you will see the rendering

Hope this helps

**Comment by amisha2016** [comment]
I am also facing the same problem. I have done it in virtual box. But the above solution didn't helped me. Ca you tell any other solution.
