### ISSUE TITLE
Mapnik "8 shaped MP" and elements inside "highway areas" not rendering

### ISSUE THREAD

**Issue by SHARCRASH** [openstreetmap/mod_tile#117]
I've encountered 2 cases where elements do not render properly in Mapnik:
- 2 areas from the same "MP relation" crossing in a single node (let's say forming like a "8" shape), even if the lines are clearly cut out at that node, apparently only the smallest area will render.
- whatever lines or areas like buildings, barriers, waterways, etc... will not render inside "highway areas", nodes are OK. It is logic though that independent "highway lines" inside such area should not be rendered.

PS: not sure if this is the right place to post this kind of issue, sorry if mistaken.

**Comment by pnorman** [comment]
> PS: not sure if this is the right place to post this kind of issue, sorry if mistaken.

No.

If you're using osm2pgsql, see https://github.com/openstreetmap/osm2pgsql, that handles conversions from OSM data into PostGIS geometries. Before reporting an issue, be sure to make sure you're on a recent version and you can provide a test which exhibits the problem.

If you're reporting an issue with a style, see the issue tracker for that style. You should be aware that most styles do nothing with multipolygons, but have them instead handled by whatever imports the data into a DB.

**Comment by SHARCRASH** [comment]
No, I'm not using OSM2PGSQL or rendering personal tiles or entire styles... I just edit in iD and noticed that the elements i described are not rendered in the "Mapnik" layer.  :)

**Comment by SomeoneElseOSM** [comment]
For completeness, there's a stylesheet rather than a software issue raised against OSM's "standard" style over at https://github.com/gravitystorm/openstreetmap-carto/issues/688 .  I suspect that this might be the problem in this case, rather than a software issue with mod_tile, osm2pgsql, mapnik etc.
