### ISSUE TITLE
mod_tile or render restriction without warning or error after zoom 30

### ISSUE THREAD

**Issue by damiendevienne** [openstreetmap/mod_tile#118]
Hello, 
It seems that for any reason, when trying to zoom in the map higher than zoom 30, the daemon is not even called. 
- I set max zoom everywhere to 40
- I changed the code everywhere to fix the problem of power of 2 being computed with `1<<z`, making values of z higher than 31 impossible (32 bit problem). Solved with using long int and pow(2,z) for computing.
- I added many print controls to gen_tiles.cpp and other source codes
  -etc... 

I managed to generate metatiles when launching `./render_list -z 34 -Z 35 --all` for example. 
But interestingly, when zoomnig in my map after zoom 30, nothing happens, as if render was not even called. There is no error message (renderd is launched with `-f` option), and none of the printf I added in gen_tiles or render_submit_queue.c are printed. 

Where is this zoom30 limitation hidden? 

Thanks a lot.

**Comment by pnorman** [comment]
> Where is this zoom30 limitation hidden?

Do the metatiles generate correctly? 

My recollection was the metatile numbering system stops at 24 or something.

If render requests aren't being received by renderd, then the limitation is somewhere in mod_tile

**Comment by damiendevienne** [comment]
@pnorman til zoom 30, the metatiles generate perfectly, so I think the problem is not with metatile numbering. I do indeed believe that the problem comes from mod_tile, maybe the connection between mod_tile and renderd. 
Because the problem comes with values of z around 30, could it be a questions of bits related to the socket? I am just guessing, I don't known anything about this...
Cheers,

**Comment by damiendevienne** [comment]
...The problem seems to be within mod_tile.c, the `tile_translate` function is also computing 2^zoom with 1<<z, which breaks everything...

**Comment by damiendevienne** [comment]
I solved issues for deep zooming. 
For information, the fact that zooming after zoom 30 is impossible is due to x and y coordinates of the tiles being larger that 2*10^9 which is not possible if these variables are typed 'int'. Changing from 'int' to 'double' (and solving all related complications) was the solution. 

If some people are interested, a version of the whole modified mod_tile is available on my github. https://github.com/damiendevienne/mod_tile_deepzoom
It compiles, even with mapnik 3.

**Comment by damiendevienne** [comment]
@SomeoneElseOSM It's hard to say. mod/tile renderd will do its job up to a very very high zoom level I think, but problems start occurring on the mapnik/postgres side from zoom 40:
It starts being slow to generate tiles (maybe postgres/postgis request for very tiny bounding box not working well?), and smooth curves start to appear a bit like 'broken' lines (a rounding problem on lat/long values I presume). 
But zoom 40 brings me to a few nanometers, which is not that bad! 
Try it here: http://lifemap.univ-lyon1.fr. Nothing to do with geography, but same tools than osm.

**Comment by StyXman** [comment]
> Try it here: http://lifemap.univ-lyon1.fr.

@damiendevienne can you include https://github.com/mlevans/leaflet-hash?
