### ISSUE TITLE
Can't make in Centos 7 mapnik 3.0.12

### ISSUE THREAD

**Issue by Dios** [openstreetmap/mod_tile#132]
Hello, I'm getting trubles to install mod_tile in Centos 7 under mapnik 3.0.12 and Boost 1.59. I also tried with 1.61 and 1.53 with same results. What am I missing?

> [root@lpena mod_tile]# make
> Making all in iniparser3.0b
> make[1]: Entering directory `/root/mod_tile/iniparser3.0b'
> make[1]: Nothing to be done for`all'.
> make[1]: Leaving directory `/root/mod_tile/iniparser3.0b'
> make[1]: Entering directory`/root/mod_tile'
> g++ -DHAVE_CONFIG_H -I. -I./includes  -pthread -DSYSTEM_LIBINIPARSER=0  -I/usr/local/include -I/usr/local/include/mapnik/agg -I/usr/local/include/mapnik -I/usr/local/include -I/usr/include -I/usr/include/freetype2 -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/libpng15 -I/usr/include/libdrm -DMAPNIK_MEMORY_MAPPED_FILE -DMAPNIK_HAS_DLCFN -DBIGINT -DBOOST_REGEX_HAS_ICU -DHAVE_JPEG -DMAPNIK_USE_PROJ4 -DHAVE_PNG -DHAVE_TIFF -DLINUX -DMAPNIK_THREADSAFE -DBOOST_SPIRIT_NO_PREDEFINED_TERMINALS=1 -DBOOST_PHOENIX_NO_PREDEFINED_TERMINALS=1 -DBOOST_SPIRIT_USE_PHOENIX_V3=1 -DNDEBUG -DHAVE_CAIRO -DGRID_RENDERER -std=c++11 -fvisibility=hidden -fvisibility-inlines-hidden -Wall -pthread -ftemplate-depth-300 -Wsign-compare -Wshadow -O3 -g -O2 -MT src/renderd-gen_tile.o -MD -MP -MF src/.deps/renderd-gen_tile.Tpo -c -o src/renderd-gen_tile.o `test -f 'src/gen_tile.cpp' || echo './'`src/gen_tile.cpp
> In file included from /usr/local/include/mapnik/map.hpp:32:0,
>                  from src/gen_tile.cpp:2:
> /usr/local/include/mapnik/params.hpp: In instantiation of ‘mapnik::value_holder::value_holder(T&&) [with T = char_&]’:
> src/gen_tile.cpp:196:32:   required from here
> /usr/local/include/mapnik/params.hpp:62:49: error: no matching function for call to ‘mapnik::util::variant<mapnik::value_null, long int, double, std::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool>::variant(char_&)’
>          : value_holder_base(std::forward<T>(obj))
>                                                  ^
> /usr/local/include/mapnik/params.hpp:62:49: note: candidates are:
> In file included from /usr/local/include/mapnik/params.hpp:29:0,
>                  from /usr/local/include/mapnik/map.hpp:32,
>                  from src/gen_tile.cpp:2:
> /usr/local/include/mapnik/util/variant.hpp:35:7: note: mapnik::util::variant<mapnik::value_null, long int, double, std::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool>::variant()
>  class variant : public mapbox::util::variant<Types...>
>        ^
> /usr/local/include/mapnik/util/variant.hpp:35:7: note:   candidate expects 0 arguments, 1 provided
> /usr/local/include/mapnik/util/variant.hpp:42:44: note: mapnik::util::variant<mapnik::value_null, long int, double, std::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool>::variant(mapbox::util::no_init)
>      using mapbox::util::variant<Types...>::variant;
>                                             ^
> /usr/local/include/mapnik/util/variant.hpp:42:44: note:   no known conversion for argument 1 from ‘char_’ to ‘mapbox::util::no_init’
> /usr/local/include/mapnik/util/variant.hpp:42:44: note: template<class T, class Traits, class Enable> mapnik::util::variant<mapnik::value_null, long int, double, std::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool>::variant(T&&)
> /usr/local/include/mapnik/util/variant.hpp:42:44: note:   template argument deduction/substitution failed:
> In file included from /usr/local/include/mapnik/util/variant.hpp:27:0,
>                  from /usr/local/include/mapnik/params.hpp:29,
>                  from /usr/local/include/mapnik/map.hpp:32,
>                  from src/gen_tile.cpp:2:
> /usr/local/include/mapnik/mapbox/variant.hpp:570:15: error: no type named ‘type’ in ‘struct std::enable_if<false, void>’
>                typename Enable = typename std::enable_ifTraits::is_valid::type>
>                ^
> In file included from /usr/local/include/mapnik/params.hpp:29:0,
>                  from /usr/local/include/mapnik/map.hpp:32,
>                  from src/gen_tile.cpp:2:
> /usr/local/include/mapnik/util/variant.hpp:35:7: note: mapnik::util::variant<mapnik::value_null, long int, double, std::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool>::variant(const mapnik::util::variant<mapnik::value_null, long int, double, std::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool>&)
>  class variant : public mapbox::util::variant<Types...>
>        ^
> /usr/local/include/mapnik/util/variant.hpp:35:7: note:   no known conversion for argument 1 from ‘char_’ to ‘const mapnik::util::variant<mapnik::value_null, long int, double, std::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool>&’
> /usr/local/include/mapnik/util/variant.hpp:35:7: note: mapnik::util::variant<mapnik::value_null, long int, double, std::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool>::variant(mapnik::util::variant<mapnik::value_null, long int, double, std::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool>&&)
> /usr/local/include/mapnik/util/variant.hpp:35:7: note:   no known conversion for argument 1 from ‘char_’ to ‘mapnik::util::variant<mapnik::value_null, long int, double, std::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool>&&’
> make[1]: *_\* [src/renderd-gen_tile.o] Error 1
> make[1]: Leaving directory `/root/mod_tile'
> make: **\* [all-recursive] Error 1

**Comment by Sattyam123** [comment]
Can anybody give me a link to download and installation instructions for mapnik 3.0.12 for centOS 7

**Comment by tomhughes** [comment]
Fixed by merging #144.
