### ISSUE TITLE
Error compiling mod_tile with latest mapnik on Ubuntu 16.04 server

### ISSUE THREAD

**Issue by damiendevienne** [openstreetmap/mod_tile#133]
Hello, 
I try to compile mod_tile but I keep getting the following error when running make: 

``` console
Makefile:1136: recipe for target 'src/renderd-gen_tile.o' failed
make[1]: Leaving directory '/home/lm/mod_tile'
Makefile: 1300: recipe for target 'all-recursive' failed
```

Inspired by some ancient issues, I typed 

``` console
export CXXFLAGS="$(mapnik-config --cflags)"
export LDFLAGS="$(mapnik-config --ldflags)"
```

before running ./autogen.sh and ./configure, but I still get the error. 
Any idea?
Cheers

**Comment by SomeoneElseOSM** [comment]
Well it worked for me http://wiki.openstreetmap.org/wiki/User:SomeoneElse/Ubuntu_1604_tileserver_load :)

Obviously the difference is you're building Mapnik from source and I'm not.  Presumably a pastebin of all of the attempted build of renderd would be useful here to see exactly what's failing.

**Comment by damiendevienne** [comment]
Well, I'd better try to start again from scratch and follow all your instructions step by step. Thanks for the link!

**Comment by suezhanglove** [comment]
how do you solve this problem?I meet this problem again!

**Comment by damiendevienne** [comment]
@suezhanglove I don't remember exactly, but I created a page explainnig how I cofigured everything for my purpose not a geographic project but some similarities). You will find what I did to install mod_tile there: http://lifemap.univ-lyon1.fr/help/setup/

**Comment by mozartvn** [comment]
@damiendevienne 
not working :(

**Comment by mozartvn** [comment]
@SomeoneElseOSM 
I have followed http://wiki.openstreetmap.org/wiki/User:SomeoneElse/Ubuntu_1604_tileserver_load
but when I compile I get issue:

`home/osm/src/mod_tile/src/gen_tile.cpp:174: undefined reference to `mapnik::freetype_engine::register_font(std::string const&)'
src/renderd-gen_tile.o: In function `render_init':
/home/osm/src/mod_tile/src/gen_tile.cpp:329: undefined reference to `mapnik::datasource_cache::register_datasources(std::string const&, bool)'
src/renderd-gen_tile.o: In function `xmlmapconfig':
/home/osm/src/mod_tile/src/gen_tile.cpp:98: undefined reference to `mapnik::Map::Map(int, int, std::string const&)'
src/renderd-gen_tile.o: In function `render_thread':
/home/osm/src/mod_tile/src/gen_tile.cpp:361: undefined reference to `mapnik::load_map(mapnik::Map&, std::string const&, bool, std::string)'
/home/osm/src/mod_tile/src/gen_tile.cpp:369: undefined reference to `mapnik::Map::srs() const'
src/renderd-gen_tile.o: In function `render':
/home/osm/src/mod_tile/src/gen_tile.cpp:277: undefined reference to `std::string mapnik::save_to_string<mapnik::image_view_any>(mapnik::image_view_any const&, std::string const&)'
src/renderd-parameterize_style.o: In function `parameterize_map_language(mapnik::Map&, char*)':
/home/osm/src/mod_tile/src/parameterize_style.cpp:48: undefined reference to `boost::optional<std::string> mapnik::parameters::get<std::string>(std::string const&) const'
collect2: error: ld returned 1 exit status
Makefile:784: recipe for target 'renderd' failed
make[1]: *** [renderd] Error 1
make[1]: Leaving directory '/home/osm/src/mod_tile'
Makefile:1300: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
osm@ubuntu:~/src/mod_tile$ export CXXFLAGS="$(mapnik-config --cflags)"
export LDFLAGS="$(mapnik-config --ldflags)"osm@ubuntu:~/src/mod_tile$ export LDFLAGS="$(mapnik-config --ldflags)"
osm@ubuntu:~/src/mod_tile$ make
Making all in iniparser3.0b
make[1]: Entering directory '/home/osm/src/mod_tile/iniparser3.0b'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/osm/src/mod_tile/iniparser3.0b'
make[1]: Entering directory '/home/osm/src/mod_tile'
/bin/bash ./libtool  --tag=CXX   --mode=link g++ -I/usr/include -I/usr/include/mapnik/agg -I/usr/include -I/usr/include/freetype2 -I/usr/include/libxml2 -I/usr/include/gdal -I/usr/include/postgresql -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/libpng12 -DMAPNIK_MEMORY_MAPPED_FILE -DMAPNIK_HAS_DLCFN -DBIGINT -DBOOST_REGEX_HAS_ICU -DHAVE_JPEG -DMAPNIK_USE_PROJ4 -DHAVE_PNG -DHAVE_WEBP -DHAVE_TIFF -DLINUX -DMAPNIK_THREADSAFE -DBOOST_SPIRIT_NO_PREDEFINED_TERMINALS=1 -DBOOST_PHOENIX_NO_PREDEFINED_TERMINALS=1 -DBOOST_SPIRIT_USE_PHOENIX_V3=1 -DNDEBUG -DHAVE_CAIRO -DGRID_RENDERER -DHAVE_LIBXML2 -std=c++11 -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g0 -Wall -pthread -Wsign-compare -Wshadow -O2 -g -O2   -o renderd src/daemon.o src/daemon_compat.o src/renderd-gen_tile.o src/sys_utils.o src/request_queue.o src/cache_expire.o src/renderd-metatile.o src/renderd-parameterize_style.o src/protocol_helper.o src/store.o src/store_file.o src/store_file_utils.o src/store_memcached.o src/store_rados.o src/store_ro_http_proxy.o src/store_ro_composite.o src/store_null.o  -pthread -L/usr/lib -lmapnik -L/usr/lib -L/usr/lib/x86_64-linux-gnu -Wl,-Bsymbolic-functions -Wl,-z,relro -g0 -pthread -lboost_filesystem -lboost_regex -lcairo -lpng -lproj -ltiff -lwebp -lxml2 -licui18n -lboost_system -lharfbuzz -ljpeg -licuuc -lfreetype -lz -ldl   -L/usr/lib/x86_64-linux-gnu -lcurl -liniparser -Liniparser3.0b/.libs -liniparser -lm 
libtool: link: g++ -I/usr/include -I/usr/include/mapnik/agg -I/usr/include -I/usr/include/freetype2 -I/usr/include/libxml2 -I/usr/include/gdal -I/usr/include/postgresql -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/libpng12 -DMAPNIK_MEMORY_MAPPED_FILE -DMAPNIK_HAS_DLCFN -DBIGINT -DBOOST_REGEX_HAS_ICU -DHAVE_JPEG -DMAPNIK_USE_PROJ4 -DHAVE_PNG -DHAVE_WEBP -DHAVE_TIFF -DLINUX -DMAPNIK_THREADSAFE -DBOOST_SPIRIT_NO_PREDEFINED_TERMINALS=1 -DBOOST_PHOENIX_NO_PREDEFINED_TERMINALS=1 -DBOOST_SPIRIT_USE_PHOENIX_V3=1 -DNDEBUG -DHAVE_CAIRO -DGRID_RENDERER -DHAVE_LIBXML2 -std=c++11 -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g0 -Wall -pthread -Wsign-compare -Wshadow -O2 -g -O2 -o .libs/renderd src/daemon.o src/daemon_compat.o src/renderd-gen_tile.o src/sys_utils.o src/request_queue.o src/cache_expire.o src/renderd-metatile.o src/renderd-parameterize_style.o src/protocol_helper.o src/store.o src/store_file.o src/store_file_utils.o src/store_memcached.o src/store_rados.o src/store_ro_http_proxy.o src/store_ro_composite.o src/store_null.o -pthread -Wl,-Bsymbolic-functions -Wl,-z -Wl,relro -g0 -pthread  -L/usr/lib -lmapnik -L/usr/lib/x86_64-linux-gnu -lboost_filesystem -lboost_regex -lcairo -lpng /usr/lib/x86_64-linux-gnu/libproj.so -ltiff -lwebp -lxml2 -licui18n -lboost_system -lharfbuzz -ljpeg -licuuc /usr/lib/x86_64-linux-gnu/libfreetype.so -lz -ldl /usr/lib/x86_64-linux-gnu/libcurl-gnutls.so -Liniparser3.0b/.libs /home/osm/src/mod_tile/iniparser3.0b/.libs/libiniparser.so -lm -pthread
src/renderd-gen_tile.o: In function `load_fonts(char const*, int)':
/home/osm/src/mod_tile/src/gen_tile.cpp:174: undefined reference to `mapnik::freetype_engine::register_font(std::string const&)'
src/renderd-gen_tile.o: In function `render_init':
/home/osm/src/mod_tile/src/gen_tile.cpp:329: undefined reference to `mapnik::datasource_cache::register_datasources(std::string const&, bool)'
src/renderd-gen_tile.o: In function `xmlmapconfig':
/home/osm/src/mod_tile/src/gen_tile.cpp:98: undefined reference to `mapnik::Map::Map(int, int, std::string const&)'
src/renderd-gen_tile.o: In function `render_thread':
/home/osm/src/mod_tile/src/gen_tile.cpp:361: undefined reference to `mapnik::load_map(mapnik::Map&, std::string const&, bool, std::string)'
/home/osm/src/mod_tile/src/gen_tile.cpp:369: undefined reference to `mapnik::Map::srs() const'
src/renderd-gen_tile.o: In function `render':
/home/osm/src/mod_tile/src/gen_tile.cpp:277: undefined reference to `std::string mapnik::save_to_string<mapnik::image_view_any>(mapnik::image_view_any const&, std::string const&)'
src/renderd-parameterize_style.o: In function `parameterize_map_language(mapnik::Map&, char*)':
/home/osm/src/mod_tile/src/parameterize_style.cpp:48: undefined reference to `boost::optional<std::string> mapnik::parameters::get<std::string>(std::string const&) const'
collect2: error: ld returned 1 exit status
Makefile:784: recipe for target 'renderd' failed
make[1]: *** [renderd] Error 1
make[1]: Leaving directory '/home/osm/src/mod_tile'
Makefile:1300: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1`

**Comment by nishantkshyp2004** [comment]
Hey, can anyone answer **mozartvn**  , I am getting the same error on Ubuntu 17.04

**Comment by SomeoneElseOSM** [comment]
@nishantkshyp2004 It must be something different that happened between downloading a .iso from Ubuntu and following the instructions - if I follow https://switch2osm.org/manually-building-a-tile-server-16-04-2-lts/ on 16.04 or https://switch2osm.org/manually-building-a-tile-server-18-04-lts/ on 18.04 I don't get the problem.  It doesn't actually surprise me that you get a problem with 17.04 as (if I remember correctly) it appeared to me that there was an issue with mismatched python-mapnik and mapnik versions in there.

Unfortunately quite a lot of things can be different - someone might have experimented with other compilers, might have upgraded from earlier versions so that some older versions of some software are in use as well, or might have set up some PPAs (UbuntuGIS perhaps - I do know that if you install that it'll break things).

Without knowing exactly what is different it's difficult to comment further.  What I'd suggest is that you download a .iso from Ubuntu, install it in a VM _exactly_ as per the 16.04 or 18.04 instructions and capture all of what you typed and what came back in a gist (not just the installation of one component).  Someone else can then do the same and we can compare the results to see why one works and another does not.
