### ISSUE TITLE
segmentation fault while rendering the file renderd.conf

### ISSUE THREAD

**Issue by SaajanJoshi** [openstreetmap/mod_tile#149]
renderd[2732]: Rendering daemon started
renderd[2732]: Initiating reqyest_queue
iniparser: syntax error in /usr/local/etc/renderd.conf (33):
-> ** config options used by mod_tile, but not renderd **
iniparser: syntax error in /usr/local/etc/renderd.conf (52):
-> ** config options used by mod_tile, but not renderd **
renderd[2732]: Parsing section renderd
renderd[2732]: Parsing render section 0
renderd[2732]: Parsing section renderd01
renderd[2732]: Parsing render section 1
renderd[2732]: Parsing section renderd02
renderd[2732]: Parsing render section 2
renderd[2732]: Parsing section mapnik
renderd[2732]: Parsing section default
renderd[2732]: Parsing section style2
renderd[2732]: config renderd: unix socketname=/var/run/renderd/renderd.sock
renderd[2732]: config renderd: num_threads=4
renderd[2732]: config renderd: num_slaves=8
renderd[2732]: config renderd: tile_dir=/var/lib/mod_tile
renderd[2732]: config renderd: stats_file=/var/run/renderd/renderd.stats
renderd[2732]: config mapnik:  plugins_dir=/usr/local/lib/mapnik/input
renderd[2732]: config mapnik:  font_dir=/usr/share/fonts/truetype/ttf-dejavu
renderd[2732]: config mapnik:  font_dir_recurse=1
renderd[2732]: config renderd(0): Active
renderd[2732]: config renderd(0): unix socketname=/var/run/renderd/renderd.sock
renderd[2732]: config renderd(0): num_threads=4
renderd[2732]: config renderd(0): tile_dir=/var/lib/mod_tile
renderd[2732]: config renderd(0): stats_file=/var/run/renderd/renderd.stats
renderd[2732]: config renderd(1): unix socketname=/var/run/renderd/renderd.sock
renderd[2732]: config renderd(1): num_threads=4
renderd[2732]: config renderd(1): tile_dir=/var/lib/mod_tile
renderd[2732]: config renderd(1): stats_file=(null)
renderd[2732]: config renderd(2): unix socketname=/var/run/renderd/renderd.sock
renderd[2732]: config renderd(2): num_threads=4
renderd[2732]: config renderd(2): tile_dir=/var/lib/mod_tile
renderd[2732]: config renderd(2): stats_file=(null)
renderd[2732]: config map 0:   name(default) file(/home/saazan/src/mapnik-style/osm.xml) uri(/osm_tiles/) htcp() host(localhost)
renderd[2732]: config map 1:   name(style2) file() uri() htcp() host()
renderd[2732]: Initialising unix server socket on /var/run/renderd/renderd.sock
renderd[2732]: Created server socket 5
renderd[2732]: Renderd is using mapnik version 3.0.9
renderd[2732]: DEBUG: Loading font: /usr/share/fonts/truetype/ttf-dejavu/DejaVuSans-ExtraLight.ttf
renderd[2732]: DEBUG: Loading font: /usr/share/fonts/truetype/ttf-dejavu/DejaVuSerif.ttf
renderd[2732]: DEBUG: Loading font: /usr/share/fonts/truetype/ttf-dejavu/DejaVuSerif-BoldItalic.ttf
renderd[2732]: DEBUG: Loading font: /usr/share/fonts/truetype/ttf-dejavu/DejaVuSerifCondensed-BoldItalic.ttf
renderd[2732]: DEBUG: Loading font: /usr/share/fonts/truetype/ttf-dejavu/DejaVuSans-Bold.ttf
renderd[2732]: DEBUG: Loading font: /usr/share/fonts/truetype/ttf-dejavu/DejaVuSansMono-BoldOblique.ttf
renderd[2732]: DEBUG: Loading font: /usr/share/fonts/truetype/ttf-dejavu/DejaVuSansMono-Bold.ttf
renderd[2732]: DEBUG: Loading font: /usr/share/fonts/truetype/ttf-dejavu/DejaVuSansMono-Oblique.ttf
renderd[2732]: DEBUG: Loading font: /usr/share/fonts/truetype/ttf-dejavu/DejaVuSerif-Italic.ttf
renderd[2732]: DEBUG: Loading font: /usr/share/fonts/truetype/ttf-dejavu/DejaVuSans.ttf
renderd[2732]: DEBUG: Loading font: /usr/share/fonts/truetype/ttf-dejavu/DejaVuSansMono.ttf
renderd[2732]: DEBUG: Loading font: /usr/share/fonts/truetype/ttf-dejavu/DejaVuSansCondensed-Oblique.ttf
renderd[2732]: DEBUG: Loading font: /usr/share/fonts/truetype/ttf-dejavu/DejaVuSerifCondensed-Italic.ttf
renderd[2732]: DEBUG: Loading font: /usr/share/fonts/truetype/ttf-dejavu/DejaVuSansCondensed-BoldOblique.ttf
renderd[2732]: DEBUG: Loading font: /usr/share/fonts/truetype/ttf-dejavu/DejaVuSansCondensed-Bold.ttf
renderd[2732]: DEBUG: Loading font: /usr/share/fonts/truetype/ttf-dejavu/DejaVuSerifCondensed.ttf
renderd[2732]: DEBUG: Loading font: /usr/share/fonts/truetype/ttf-dejavu/DejaVuSans-Oblique.ttf
renderd[2732]: DEBUG: Loading font: /usr/share/fonts/truetype/ttf-dejavu/DejaVuSerifCondensed-Bold.ttf
renderd[2732]: DEBUG: Loading font: /usr/share/fonts/truetype/ttf-dejavu/DejaVuSansCondensed.ttf
renderd[2732]: DEBUG: Loading font: /usr/share/fonts/truetype/ttf-dejavu/DejaVuSerif-Bold.ttf
renderd[2732]: DEBUG: Loading font: /usr/share/fonts/truetype/ttf-dejavu/DejaVuSans-BoldOblique.ttf
Running in foreground mode...
renderd[2732]: Initialising unix client socket on /var/run/renderd/renderd.sockrenderd[2732]: Starting stats thread

debug: init_storage_backend: initialising file storage backend at: /var/lib/mod_tile
renderd[2732]: Loading parameterization function for 
debug: init_storage_backend: initialising file storage backend at: /var/lib/mod_tile
renderd[2732]: Loading parameterization function for 
renderd[2732]: Initialising unix client socket on /var/run/renderd/renderd.sock
debug: init_storage_backend: initialising file storage backend at: /var/lib/mod_tile
debug: init_storage_backend: initialising file storage backend at: /var/lib/mod_tile
renderd[2732]: Loading parameterization function for 
renderd[2732]: Loading parameterization function for 
renderd[2732]: socket /var/run/renderd/renderd.sock initialised to fd 9
renderd[2732]: Initialising unix client socket on /var/run/renderd/renderd.sock
renderd[2732]: Initialising unix client socket on /var/run/renderd/renderd.sock
renderd[2732]: Initialising unix client socket on /var/run/renderd/renderd.sock
renderd[2732]: Initialising unix client socket on /var/run/renderd/renderd.sock
renderd[2732]: DEBUG: Got incoming connection, fd 16, number 1
renderd[2732]: DEBUG: Got incoming connection, fd 20, number 2
renderd[2732]: DEBUG: Got incoming connection, fd 21, number 3
renderd[2732]: socket /var/run/renderd/renderd.sock initialised to fd 22renderd[2732]: DEBUG: Got incoming connection, fd 24, number 4
renderd[2732]: DEBUG: Got incoming connection, fd 25, number 5

renderd[2732]: DEBUG: Got incoming connection, fd 27, number 6
renderd[2732]: socket /var/run/renderd/renderd.sock initialised to fd 26
renderd[2732]: socket /var/run/renderd/renderd.sock initialised to fd 6
renderd[2732]: Initialising unix client socket on /var/run/renderd/renderd.sock
renderd[2732]: DEBUG: Got incoming connection, fd 29, number 7
renderd[2732]: socket /var/run/renderd/renderd.sock initialised to fd 28
renderd[2732]: Initialising unix client socket on /var/run/renderd/renderd.sock
renderd[2732]: socket /var/run/renderd/renderd.sock initialised to fd 17renderd[2732]: socket /var/run/renderd/renderd.sock initialised to fd 23

renderd[2732]: DEBUG: Got incoming connection, fd 14, number 8
renderd[2732]: socket /var/run/renderd/renderd.sock initialised to fd 11
Mapnik LOG> 2016-12-28 08:44:03: warning: unable to find face-name 'unifont Medium' in FontSet 'book-fonts'
Mapnik LOG> 2016-12-28 08:44:03: warning: unable to find face-name 'unifont Medium' in FontSet 'bold-fonts'
Mapnik LOG> 2016-12-28 08:44:03: warning: unable to find face-name 'unifont Medium' in FontSet 'oblique-fonts'
Mapnik LOG> 2016-12-28 08:44:03: warning: unable to find face-name 'unifont Medium' in FontSet 'book-fonts'
Mapnik LOG> 2016-12-28 08:44:03: warning: unable to find face-name 'unifont Medium' in FontSet 'bold-fonts'
Mapnik LOG> 2016-12-28 08:44:03: warning: unable to find face-name 'unifont Medium' in FontSet 'oblique-fonts'
Mapnik LOG> 2016-12-28 08:44:03: warning: unable to find face-name 'unifont Medium' in FontSet 'book-fonts'
Mapnik LOG> 2016-12-28 08:44:03: warning: unable to find face-name 'unifont Medium' in FontSet 'bold-fonts'
Mapnik LOG> 2016-12-28 08:44:03: warning: unable to find face-name 'unifont Medium' in FontSet 'oblique-fonts'
Mapnik LOG> 2016-12-28 08:44:03: warning: unable to find face-name 'unifont Medium' in FontSet 'book-fonts'
Mapnik LOG> 2016-12-28 08:44:03: warning: unable to find face-name 'unifont Medium' in FontSet 'bold-fonts'
Mapnik LOG> 2016-12-28 08:44:03: warning: unable to find face-name 'unifont Medium' in FontSet 'oblique-fonts'
Segmentation fault

**Comment by wmyrda** [comment]
I also get "Segmentation fault". In my case I updated mapnik & python-mapnik to the git master and obviously previously compiled about 6 months ago mod_tile would not work with present mapnik. The recompile with new mapnik also fails. See https://github.com/openstreetmap/mod_tile/issues/164

**Comment by xamanu** [comment]
Can you please try with a recent version and check if the problem still persists?
