### ISSUE TITLE
renderd stuck: renderd[14342]: Loading parameterization function for  Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by suezhanglove** [openstreetmap/mod_tile#151]
i check my log carefully, i find this lines.Can anybody help me to solve this problem? Thanks a lot!
`renderd[14342]: Created server socket 5
renderd[14342]: Renderd is using mapnik version 3.1.0
Mapnik LOG> 2017-01-08 13:53:55: register_datasources: boost::filesystem::directory_iterator::construct: No such file or directory`

this is my log.
`renderd[14342]: Rendering daemon started
renderd[14342]: Initiating reqyest_queue
renderd[14342]: Parsing section renderd
renderd[14342]: Parsing render section 0
renderd[14342]: Parsing section mapnik
renderd[14342]: Parsing section default
renderd[14342]: config renderd: unix socketname=/var/run/renderd/renderd.sock
renderd[14342]: config renderd: num_threads=4
renderd[14342]: config renderd: num_slaves=0
renderd[14342]: config renderd: tile_dir=/var/lib/mod_tile
renderd[14342]: config renderd: stats_file=/var/run/renderd/renderd.stats
renderd[14342]: config mapnik:  plugins_dir=/usr/lib/mapnik/3.0/input
renderd[14342]: config mapnik:  font_dir=/usr/share/fonts/truetype
renderd[14342]: config mapnik:  font_dir_recurse=1
renderd[14342]: config renderd(0): Active
renderd[14342]: config renderd(0): unix socketname=/var/run/renderd/renderd.sock
renderd[14342]: config renderd(0): num_threads=4
renderd[14342]: config renderd(0): tile_dir=/var/lib/mod_tile
renderd[14342]: config renderd(0): stats_file=/var/run/renderd/renderd.stats
renderd[14342]: config map 0:   name(default) file(/home/zs/openstreetmap-carto-2.41.0/style.xml) uri(/osm_tiles/) htcp() host(localhost)
renderd[14342]: Initialising unix server socket on /var/run/renderd/renderd.sock
renderd[14342]: Created server socket 5
renderd[14342]: Renderd is using mapnik version 3.1.0
Mapnik LOG> 2017-01-08 13:53:55: register_datasources: boost::filesystem::directory_iterator::construct: No such file or directory
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/liberation/LiberationSansNarrow-Regular.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/liberation/LiberationSans-BoldItalic.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/liberation/LiberationSansNarrow-BoldItalic.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/liberation/LiberationSerif-Bold.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/liberation/LiberationMono-Regular.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/liberation/LiberationSans-Bold.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/liberation/LiberationMono-Bold.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/liberation/LiberationSansNarrow-Italic.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/liberation/LiberationSerif-Regular.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/liberation/LiberationMono-Italic.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/liberation/LiberationSerif-Italic.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/liberation/LiberationSans-Italic.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/liberation/LiberationSerif-BoldItalic.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/liberation/LiberationMono-BoldItalic.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/liberation/LiberationSansNarrow-Bold.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/fonts-japanese-gothic.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/ttf-khmeros-core/KhmerOS.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/ttf-khmeros-core/KhmerOSsys.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/sinhala/lklug.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/unifont/unifont_csur.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/unifont/unifont.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/unifont/unifont_upper.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/unifont/unifont_sample.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/unifont/unifont_upper_csur.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/lao/Phetsarath_OT.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/ubuntu-font-family/UbuntuMono-RI.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/ubuntu-font-family/Ubuntu-LI.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/ubuntu-font-family/Ubuntu-M.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/ubuntu-font-family/Ubuntu-BI.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/ubuntu-font-family/UbuntuMono-BI.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/ubuntu-font-family/Ubuntu-MI.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/ubuntu-font-family/UbuntuMono-B.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/ubuntu-font-family/Ubuntu-L.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/ubuntu-font-family/Ubuntu-R.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/ubuntu-font-family/Ubuntu-B.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/ubuntu-font-family/UbuntuMono-R.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/ubuntu-font-family/Ubuntu-RI.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/ubuntu-font-family/Ubuntu-C.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/tlwg/Umpush-Oblique.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/tlwg/Sawasdee-Oblique.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/tlwg/Kinnari-Italic.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/tlwg/Garuda.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/tlwg/Umpush-BoldOblique.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/tlwg/Umpush-Light.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/tlwg/Kinnari.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/tlwg/Laksaman-Bold.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/tlwg/Norasi-Italic.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/tlwg/TlwgTypo-BoldOblique.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/tlwg/TlwgTypewriter.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/tlwg/Norasi.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/tlwg/Loma-BoldOblique.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/tlwg/Umpush.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/tlwg/Sawasdee-Bold.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/tlwg/Sawasdee-BoldOblique.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/tlwg/Laksaman.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/tlwg/TlwgTypo.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/tlwg/Norasi-BoldItalic.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/tlwg/Purisa-BoldOblique.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/tlwg/Garuda-Bold.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/tlwg/TlwgTypewriter-BoldOblique.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/tlwg/Loma-Oblique.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/tlwg/Waree-Bold.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/tlwg/TlwgMono.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/tlwg/TlwgMono-BoldOblique.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/tlwg/Norasi-Bold.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/tlwg/Sawasdee.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/tlwg/Loma-Bold.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/tlwg/Purisa-Oblique.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/tlwg/Kinnari-BoldOblique.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/tlwg/Laksaman-Italic.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/tlwg/Norasi-Oblique.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/tlwg/TlwgTypo-Oblique.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/tlwg/Garuda-BoldOblique.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/tlwg/Kinnari-Bold.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/tlwg/Garuda-Oblique.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/tlwg/Waree-Oblique.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/tlwg/Waree-BoldOblique.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/tlwg/TlwgTypist-BoldOblique.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/tlwg/TlwgTypewriter-Bold.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/tlwg/Waree.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/tlwg/Umpush-Bold.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/tlwg/TlwgTypo-Bold.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/tlwg/Loma.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/tlwg/Purisa-Bold.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/tlwg/Kinnari-Oblique.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/tlwg/TlwgTypist.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/tlwg/TlwgTypist-Bold.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/tlwg/TlwgTypist-Oblique.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/tlwg/TlwgMono-Bold.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/tlwg/TlwgMono-Oblique.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/tlwg/Purisa.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/tlwg/Norasi-BoldOblique.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/tlwg/Kinnari-BoldItalic.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/tlwg/Laksaman-BoldItalic.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/tlwg/TlwgTypewriter-Oblique.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/tlwg/Umpush-LightOblique.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/fonts-guru-extra/Saab.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/kacst-one/KacstOne.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/kacst-one/KacstOne-Bold.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/openoffice/opens___.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/tibetan-machine/TibetanMachineUni.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/takao-gothic/TakaoPGothic.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/ttf-dejavu/DejaVuSerif-Italic.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/ttf-dejavu/DejaVuSans-BoldOblique.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/ttf-dejavu/DejaVuSerif-BoldItalic.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/ttf-dejavu/DejaVuSansMono-BoldOblique.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/ttf-dejavu/DejaVuSerif.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/ttf-dejavu/DejaVuSans-Bold.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/ttf-dejavu/DejaVuSerifCondensed-BoldItalic.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/ttf-dejavu/DejaVuSans-Oblique.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/ttf-dejavu/DejaVuSans.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/ttf-dejavu/DejaVuSansMono.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/ttf-dejavu/DejaVuSerifCondensed-Italic.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/ttf-dejavu/DejaVuSansMono-Oblique.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/ttf-dejavu/DejaVuSerifCondensed.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/ttf-dejavu/DejaVuSerifCondensed-Bold.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/ttf-dejavu/DejaVuSansCondensed-Bold.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/ttf-dejavu/DejaVuSansCondensed-Oblique.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/ttf-dejavu/DejaVuSansCondensed.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/ttf-dejavu/DejaVuSansCondensed-BoldOblique.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/ttf-dejavu/DejaVuSerif-Bold.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/ttf-dejavu/DejaVuSans-ExtraLight.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/ttf-dejavu/DejaVuSansMono-Bold.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/lohit-punjabi/Lohit-Punjabi.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/nanum/NanumMyeongjo.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/nanum/NanumMyeongjoBold.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/nanum/NanumBarunGothicBold.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/nanum/NanumGothic.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/nanum/NanumGothicBold.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/nanum/NanumBarunGothic.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/freefont/FreeMonoBold.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/freefont/FreeMonoOblique.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/freefont/FreeSerifBoldItalic.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/freefont/FreeSerif.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/freefont/FreeMonoBoldOblique.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/freefont/FreeSansOblique.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/freefont/FreeMono.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/freefont/FreeSansBoldOblique.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/freefont/FreeSerifItalic.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/freefont/FreeSans.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/freefont/FreeSerifBold.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/freefont/FreeSansBold.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/kacst/mry_KacstQurn.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/kacst/KacstFarsi.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/kacst/KacstTitle.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/kacst/KacstQurn.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/kacst/KacstLetter.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/kacst/KacstTitleL.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/kacst/KacstScreen.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/kacst/KacstPoster.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/kacst/KacstPen.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/kacst/KacstNaskh.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/kacst/KacstDecorative.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/kacst/KacstBook.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/kacst/KacstDigital.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/kacst/KacstArt.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/kacst/KacstOffice.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/abyssinica/AbyssinicaSIL-R.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/ancient-scripts/Symbola_hint.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/padauk/Padauk-bold.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/padauk/Padauk-book.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/padauk/Padauk-bookbold.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/padauk/Padauk.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/dejavu/DejaVuSerif-Italic.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/dejavu/DejaVuSans-BoldOblique.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/dejavu/DejaVuSerif-BoldItalic.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/dejavu/DejaVuSansMono-BoldOblique.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/dejavu/DejaVuSerif.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/dejavu/DejaVuSerifCondensed-BoldItalic.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/dejavu/DejaVuSans-Oblique.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/dejavu/DejaVuSans.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/dejavu/DejaVuSerifCondensed-Italic.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/dejavu/DejaVuSansMono-Oblique.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/dejavu/DejaVuSerifCondensed.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/dejavu/DejaVuSerifCondensed-Bold.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/dejavu/DejaVuSansCondensed-Bold.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/dejavu/DejaVuSansCondensed-Oblique.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/dejavu/DejaVuSansCondensed.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/dejavu/DejaVuSansCondensed-BoldOblique.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/dejavu/DejaVuSerif-Bold.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/dejavu/DejaVuSans-ExtraLight.ttf
renderd[14342]: DEBUG: Loading font: /usr/share/fonts/truetype/dejavu/DejaVuSansMono-Bold.ttf
Running in foreground mode...
debug: init_storage_backend: initialising file storage backend at: /var/lib/mod_tile
renderd[14342]: Loading parameterization function for 
renderd[14342]: Starting stats thread
debug: init_storage_backend: initialising file storage backend at: /var/lib/mod_tile
debug: init_storage_backend: initialising file storage backend at: /var/lib/mod_tile
renderd[14342]: Loading parameterization function for 
renderd[14342]: Loading parameterization function for 
debug: init_storage_backend: initialising file storage backend at: /var/lib/mod_tile
renderd[14342]: Loading parameterization function for 
Segmentation fault (core dumped)
`

**Comment by xamanu** [comment]
Closed because of inactivity. Please try again with a recent version and let us know if any problems persist.
