### ISSUE TITLE
Query realted to Tile Server 

### ISSUE THREAD

**Issue by abhit011** [openstreetmap/mod_tile#153]
Hello * 

I dont know if this is the right forum or not, but I am trying building tile server on Ubuntu 16.04 and idea is to get it hosted on my own server. 
Need some info , does Tile Server support the snapshot like what google static map api provides.
e.g something like this 

> http://maps.googleapis.com/maps/api/staticmap?size=400x400&zoom=15&path=28.376618,76.831307%7C28.376073,76.830382%7C28.376073,76.830382%7C28.375747,76.830693%7C28.375367,76.831867%7C28.374878,76.833351%7C28.374536,76.834409%7C28.373980,76.836178%7C28.374536,76.834409%7C28.373582,76.837413%7C28.373153,76.838907%7C28.373018,76.840596&sensor=false

Is it possible ? In tile server or I have to do something else ?

Thanks
!wq
Abhi

**Comment by woodpeck** [comment]
This is not a forum, this is a site for reporting bugs in mod_tile. The answer is no, mod_tile doesn't support static maps. There are some third-party programs that you can use on top of your tile server to offer static maps capability, see http://wiki.openstreetmap.org/wiki/Static_map_images
