### ISSUE TITLE
Improved defauits for renderd.conf

### ISSUE THREAD

**Issue by PanderMusubi** [openstreetmap/mod_tile#159]
Improved defauits for renderd.conf are

    plugins_dir=/usr/lib/mapnik/input

should become

    plugins_dir=/usr/lib/mapnik/3.0/input

and when `apt-get install openstreetmap-carto-common` is done

    XML=/home/jburgess/osm/svn.openstreetmap.org/applications/rendering/mapnik/osm-local.xml

should become

    XML=/usr/share/openstreetmap-carto-common/style.xml

Also installing packages openstreetmap-carto-common and openstreetmap-carto could be discussed a bit in the documentation here.

**Comment by SomeoneElseOSM** [comment]
@PanderMusubi It might also be worth a look at https://github.com/SomeoneElseOSM/mod_tile - I've tidied up a number of issues such as these in there, designed to make it easier for people to set up a tile server for the first time.

**Comment by PanderMusubi** [comment]
Nice! Time to merge?

**Comment by PanderMusubi** [comment]
@SomeoneElseOSM the current version of your fork does not compile unfortunately on Ubuntu 17.04:

    In file included from /usr/include/mapnik/map.hpp:32:0,
                     from src/gen_tile.cpp:2:
    /usr/include/mapnik/params.hpp: In instantiation of ‘mapnik::value_holder::value_holder(T&&) [with T = char*&]’:
    src/gen_tile.cpp:196:34:   required from here
    /usr/include/mapnik/params.hpp:62:49: error: no matching function for call to ‘mapnik::util::variant<mapnik::value_null, long int, double, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool>::variant(char*&)’
             : value_holder_base(std::forward<T>(obj))
                                                     ^
    In file included from /usr/include/mapnik/params.hpp:29:0,
                     from /usr/include/mapnik/map.hpp:32,
                     from src/gen_tile.cpp:2:
    /usr/include/mapnik/util/variant.hpp:42:44: note: candidate: mapnik::util::variant<mapnik::value_null, long int, double, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool>::variant(mapbox::util::no_init)
         using mapbox::util::variant<Types...>::variant;
                                                ^~~~~~~
    /usr/include/mapnik/util/variant.hpp:42:44: note:   no known conversion for argument 1 from ‘char*’ to ‘mapbox::util::no_init’
    /usr/include/mapnik/util/variant.hpp:42:44: note: candidate: template<class T, class Traits, class Enable> mapnik::util::variant<mapnik::value_null, long int, double, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool>::variant(T&&)
    /usr/include/mapnik/util/variant.hpp:42:44: note:   template argument deduction/substitution failed:
    In file included from /usr/include/mapnik/util/variant.hpp:27:0,
                     from /usr/include/mapnik/params.hpp:29,
                     from /usr/include/mapnik/map.hpp:32,
                     from src/gen_tile.cpp:2:
    /usr/include/mapbox/variant.hpp:598:15: error: no type named ‘type’ in ‘struct std::enable_if<false, void>’
                   typename Enable = typename std::enable_if<Traits::is_valid && !std::is_same<variant<Types...>, typename Traits::value_type>::value>::type >
                   ^~~~~~~~
    In file included from /usr/include/mapnik/params.hpp:29:0,
                     from /usr/include/mapnik/map.hpp:32,
                     from src/gen_tile.cpp:2:
    /usr/include/mapnik/util/variant.hpp:35:7: note: candidate: mapnik::util::variant<mapnik::value_null, long int, double, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool>::variant()
     class variant : public mapbox::util::variant<Types...>
           ^~~~~~~

**Comment by SomeoneElseOSM** [comment]
That doesn't surprise me to be honest - I'll have a look at it at some point, but probably not until 18.04 LTS is out.

**Comment by PanderMusubi** [comment]
is there a certain commit that does compile?
