### ISSUE TITLE
render_list output directory

### ISSUE THREAD

**Issue by rahimramezanian** [openstreetmap/mod_tile#161]
Hi. Is it possible to change the output directory of render_list from /var/lib/mod_tile?
Thanks.

**Comment by woodpeck** [comment]
This issue tracker is for reporting problems with the software, not for asking questions about how to use the software. Use the https://lists.openstreetmap.org/listinfo/tile-serving mailing list or help.openstreetmap.org to ask questions.

The answer to your question is no, you cannot change this in render_list, you have to change it in renderd.conf and it then applies to all tile rendering on the server, not only that triggered by render_list. What you *can* do is create a new map style in renderd.conf that is an identical copy of your main map style. Then use that new style with render_list and the tiles will end up in /var/lib/mod_tile/your_new_style.

**Comment by rahimramezanian** [comment]
Thanks and sorry for the inappropriate issue
