### ISSUE TITLE
Wc++14-extensions 

### ISSUE THREAD

**Issue by Mrsevic** [openstreetmap/mod_tile#163]
I recieve this unrecognized command error. I have the newest g++ installed. I tried to solve the problem but I was not able to do so:

-fvisibility-inlines-hidden -Wall -pthread -ftemplate-depth-300 -Wsign-compare -Wc++14-extensions -O3 -g -O2 -MT src/renderd-gen_tile.o -MD -MP -MF src/.deps/renderd-gen_tile.Tpo -c -o src/renderd-gen_tile.o `test -f 'src/gen_tile.cpp' || echo './'`src/gen_tile.cpp
g++.real: error: unrecognized command line option ‘-Wc++14-extensions’
Makefile:1136: recipe for target 'src/renderd-gen_tile.o' failed
make[1]: *** [src/renderd-gen_tile.o] Error 1
make[1]: Leaving directory '/home/tileserver/src/mod_tile'
Makefile:1300: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by drkameleon** [comment]
Just opened `Makefile` and edited `-Wc++14-extensions` out. 

Seems to be moving on fine...

**Comment by Mrsevic** [comment]
Thanks.

**Comment by Wavfact** [comment]
I too am getting this same issue.. but editing out the "-Wc++14-extensions" from the Makefile only gives me more errors..  

rc/.deps/renderd-gen_tile.Tpo -c -o src/renderd-gen_tile.o `test -f 'src/gen_tile.                                                                                                                                                           cpp' || echo './'`src/gen_tile.cpp
In file included from /usr/local/include/mapnik/map.hpp:32:0,
                 from src/gen_tile.cpp:2:
/usr/local/include/mapnik/params.hpp: In instantiation of ‘mapnik::value_holder::v                                                                                                                                                           alue_holder(T&&) [with T = char*&]’:
src/gen_tile.cpp:196:34:   required from here
/usr/local/include/mapnik/params.hpp:62:49: error: no matching function for call t                                                                                                                                                           o ‘mapbox::util::variant<mapnik::value_null, long int, double, std::basic_string<c                                                                                                                                                           har, std::char_traits<char>, std::allocator<char> >, bool>::variant(char*&)’
         : value_holder_base(std::forward<T>(obj))
                                                 ^
In file included from /usr/local/include/mapnik/util/variant.hpp:27:0,
                 from /usr/local/include/mapnik/params.hpp:29,
                 from /usr/local/include/mapnik/map.hpp:32,
                 from src/gen_tile.cpp:2:
/usr/local/include/mapnik/mapbox/variant.hpp:624:20: note: candidate: mapbox::util                                                                                                                                                           ::variant<Types>::variant(mapbox::util::variant<Types>&&) [with Types = {mapnik::v                                                                                                                                                           alue_null, long int, double, std::basic_string<char, std::char_traits<char>, std::                                                                                                                                                           allocator<char> >, bool}]
     VARIANT_INLINE variant(variant<Types...>&& old)
                    ^~~~~~~
/usr/local/include/mapnik/mapbox/variant.hpp:624:20: note:   no known conversion f                                                                                                                                                           or argument 1 from ‘char*’ to ‘mapbox::util::variant<mapnik::value_null, long int,                                                                                                                                                            double, std::basic_string<char, std::char_traits<char>, std::allocator<char> >, b                                                                                                                                                           ool>&&’
/usr/local/include/mapnik/mapbox/variant.hpp:618:20: note: candidate: mapbox::util                                                                                                                                                           ::variant<Types>::variant(const mapbox::util::variant<Types>&) [with Types = {mapn                                                                                                                                                           ik::value_null, long int, double, std::basic_string<char, std::char_traits<char>,                                                                                                                                                            std::allocator<char> >, bool}]
     VARIANT_INLINE variant(variant<Types...> const& old)
                    ^~~~~~~
/usr/local/include/mapnik/mapbox/variant.hpp:618:20: note:   no known conversion f                                                                                                                                                           or argument 1 from ‘char*’ to ‘const mapbox::util::variant<mapnik::value_null, lon                                                                                                                                                           g int, double, std::basic_string<char, std::char_traits<char>, std::allocator<char                                                                                                                                                           > >, bool>&’
/usr/local/include/mapnik/mapbox/variant.hpp:612:20: note: candidate: template<cla                                                                                                                                                           ss T, class Traits, class Enable> mapbox::util::variant<Types>::variant(T&&)
     VARIANT_INLINE variant(T&& val) noexcept(std::is_nothrow_constructible<typena                                                                                                                                                           me Traits::target_type, T&&>::value)
                    ^~~~~~~
/usr/local/include/mapnik/mapbox/variant.hpp:612:20: note:   template argument ded                                                                                                                                                           uction/substitution failed:
/usr/local/include/mapnik/mapbox/variant.hpp:611:15: error: no type named ‘type’ i                                                                                                                                                           n ‘struct std::enable_if<false, void>’
               typename Enable = typename std::enable_if<Traits::is_valid && !std:                                                                                                                                                           :is_same<variant<Types...>, typename Traits::value_type>::value>::type >
               ^~~~~~~~
/usr/local/include/mapnik/mapbox/variant.hpp:606:20: note: candidate: mapbox::util                                                                                                                                                           ::variant<Types>::variant(mapbox::util::no_init) [with Types = {mapnik::value_null                                                                                                                                                           , long int, double, std::basic_string<char, std::char_traits<char>, std::allocator                                                                                                                                                           <char> >, bool}]
     VARIANT_INLINE variant(no_init) noexcept
                    ^~~~~~~
/usr/local/include/mapnik/mapbox/variant.hpp:606:20: note:   no known conversion f                                                                                                                                                           or argument 1 from ‘char*’ to ‘mapbox::util::no_init’
/usr/local/include/mapnik/mapbox/variant.hpp:599:20: note: candidate: mapbox::util                                                                                                                                                           ::variant<Types>::variant() [with Types = {mapnik::value_null, long int, double, s                                                                                                                                                           td::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool}]
     VARIANT_INLINE variant() noexcept(std::is_nothrow_default_constructible<first                                                                                                                                                           _type>::value)
                    ^~~~~~~
/usr/local/include/mapnik/mapbox/variant.hpp:599:20: note:   candidate expects 0 a                                                                                                                                                           rguments, 1 provided
Makefile:1136: recipe for target 'src/renderd-gen_tile.o' failed
make[1]: *** [src/renderd-gen_tile.o] Error 1
make[1]: Leaving directory '/home/dennis/src/mod_tile'
Makefile:1300: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
