### ISSUE TITLE
Couldn't install mod_tile on CentOS 7

### ISSUE THREAD

**Issue by NicHerndon** [openstreetmap/mod_tile#167]
I tried to install mod_tile on CentOS 7 using two different compilers. With version 4.8.5 I got the error, "unrecognized command line option ‘-std=c++14’." With version 6.2.1 I got the error, "Could not find a c++ compiler." Attached is the script with the commands issued and the output. Any suggestions on how to address this?
[mod_tile_script.txt](https://github.com/openstreetmap/mod_tile/files/1252574/mod_tile_script.txt)

**Comment by CepKo84** [comment]
I have same problem with Centos 7.
I tried clang and g++ with other versions

**Comment by EduRam** [comment]
//  I have these notes, but i do not remember if it applies.

$ scl enable devtoolset-7 bash
$ git clone git://github.com/openstreetmap/mod_tile.git
$ cd mod_tile
$ ./autogen.sh
$ ./configure

// if the above "configure" command does not work.
$ ./configure CXX=g++ CC=gcc

**Comment by xamanu** [comment]
Is this still a problem, or does compilation on CentOS work with the provided hint?
