### ISSUE TITLE
Error while running make for mod_tile

### ISSUE THREAD

**Issue by Sachithj22** [openstreetmap/mod_tile#173]
I get below error message while running make for mode_tile,

g++ -DHAVE_CONFIG_H -I. -I./includes  -pthread -DSYSTEM_LIBINIPARSER=0  -I/usr/local/include -I/usr/local/include/mapnik/agg -I/usr/local/include/mapnik -I/intucell/osm/mapnik/mason_packages/.link/include -I/intucell/osm/mapnik/mason_packages/.link/include/freetype2 -I/intucell/osm/mapnik/mason_packages/.link/include/libpng16 -I/intucell/osm/mapnik/mason_packages/linux-x86_64/libgdal/2.1.3/include -I/intucell/osm/mapnik/mason_packages/.link/include/cairo -I/intucell/osm/mapnik/mason_packages/.link/include/pixman-1 -DMAPNIK_MEMORY_MAPPED_FILE -DMAPNIK_HAS_DLCFN -DBIGINT -DBOOST_REGEX_HAS_ICU -DHAVE_JPEG -DMAPNIK_USE_PROJ4 -DHAVE_PNG -DHAVE_WEBP -DHAVE_TIFF -DLINUX -DMAPNIK_THREADSAFE -DBOOST_SPIRIT_NO_PREDEFINED_TERMINALS=1 -DBOOST_PHOENIX_NO_PREDEFINED_TERMINALS=1 -DBOOST_SPIRIT_USE_PHOENIX_V3=1 -DNDEBUG -DHAVE_CAIRO -DGRID_RENDERER -DSVG_RENDERER -std=c++14 -D_GLIBCXX_USE_CXX11_ABI=0 -fvisibility=hidden -fvisibility-inlines-hidden -Wall -pthread -ftemplate-depth-300 -Wsign-compare -O3 -g -O2 -MT src/renderd-gen_tile.o -MD -MP -MF src/.deps/renderd-gen_tile.Tpo -c -o src/renderd-gen_tile.o `test -f 'src/gen_tile.cpp' || echo './'`src/gen_tile.cpp
g++: error: unrecognized command line option ‘-std=c++14’
make[1]: *** [src/renderd-gen_tile.o] Error 1
make[1]: Leaving directory `/intucell/osm/mod_tile'
make: *** [all-recursive] Error 1

**Comment by Sachithj22** [comment]
This was fixed after I edited to c++11 in Makefile but I get different error message now,
libtool: link: warning: library `/intucell/osm/mapnik/mason_packages/.link/lib/libwebp.la' was moved.
libtool: link: warning: library `/intucell/osm/mapnik/mason_packages/.link/lib/libjpeg.la' was moved.
libtool: link: warning: library `/intucell/osm/mapnik/mason_packages/.link/lib/libfreetype.la' was moved.
libtool: link: warning: library `/intucell/osm/mapnik/mason_packages/.link/lib/libcairo.la' was moved.
libtool: link: cannot find the library `/home/travis/build/mapbox/mason/mason_packages/linux-x86_64/pixman/0.34.0/lib/libpixman-1.la' or unhandled argument `/home/travis/build/mapbox/mason/mason_packages/linux-x86_64/pixman/0.34.0/lib/libpixman-1.la'
make[1]: *** [renderd] Error 1
make[1]: Leaving directory `/intucell/osm/mod_tile'
make: *** [all-recursive] Error 1
intucell@sonbu-38:/intucell/osm/mod_tile$

**Comment by lmcewan** [comment]
I've been getting the same error. I'm not sure why, but they've configured mapnik to search for files from a "travis" home directory. Kind of hacky, but I decided to create a /home/travis/build/mapbox/mason/ directory structure, and then create a soft-link from /home/travis/build/mapbox/mason/ to /*wherever_you_cloned_mapnik*/mapnik/mason_packages with:
`ln -s /*wherever_you_cloned_mapnik*/mapnik/mason_packages /home/travis/build/mapbox/mason/`

**Comment by djnotes** [comment]
@lmcewan you did a fantastic fix
