### ISSUE TITLE
How to use protocol version 3?

### ISSUE THREAD

**Issue by paazmaya** [openstreetmap/mod_tile#176]
Seems like the protocol version 2 is being updated to version 3, by adding a png mimetype.

Is there a way to configure, perhaps via `renderd.conf` to use directly the protocol version 3 and use the mimetype specified via `TYPE` property?

I am having issues in rendering png and cannot seem to be able to use any other raster type due to that forceful mimetype setting in protocol version automated migration in https://github.com/openstreetmap/mod_tile/blob/master/src/daemon.c#L100

**Comment by SomeoneElseOSM** [comment]
@paazmaya Would it be possible to include a few more details (e.g. "protocol 3 of what") so that anyone who stumbles across this issue has a bit more idea of the context?  Also perhaps the system info where you're having problems rendering .pngs?

**Comment by paazmaya** [comment]
Thanks for the suggestion @SomeoneElseOSM, I will try to add pieces..

This commit added a "protocol version 3", https://github.com/openstreetmap/mod_tile/commit/fdc317a8f36f001d3eb2a864eb7cff55f11fdeb7

While I have compiled the `master` of mod_file and have Mapnik v3.0.18 installed, running `sudo renderd -f` displays requests with png mimetype, such as

```
renderd[27281]: DEBUG: Got incoming request with protocol version 2
renderd[27281]: DEBUG: Got command RenderBulk fd(14) xml(default), z(13), x(4662), y(2371), mime(image/png), options()
terminate called after throwing an instance of 'mapnik::image_writer_exception'
  what():  Mapnik does not support grayscale images for png
Aborted
```

Whil the counterpart in httpd/error_log is:

```
tile_translate: testing baseuri(/osm/) name(default) extension(jpg),
```

And the Leaflef.js based map requests the tiles as jpg files.

The mapnik configuration also has the `format` property set to `jpeg`.

The cause for trying to render png images, is in my understanding due to the incoming request using the "protocol version 2".

**Comment by SomeoneElseOSM** [comment]
Just as an extra data point, I've installed machines using [these instructions](https://switch2osm.org/manually-building-a-tile-server-18-04-lts/) and also [these](https://wiki.openstreetmap.org/wiki/User:SomeoneElse/Ubuntu_1804_tileserver_load) without hitting the problem you describe.  The mapnik version there according to "mapnik-config -v" is 3.0.18.

In both cases I'm using a fork rather than https://github.com/openstreetmap/mod_tile - the "switch2osm" branch of https://github.com/SomeoneElseOSM/mod_tile , but the differences are mostly to do with defaults in config files and shouldn't affect your issue.

**Comment by paazmaya** [comment]
@SomeoneElseOSM thanks for the pointers.
I rebuilt my version and got it working.

While the question was about protocol version usage, this issue can be closed as there is no likely an answer, due to the above mentioned automated protocol version migration in runtime.

**Comment by waldo22** [comment]
FYI @SomeoneElseOSM @paazmaya I had this exact same problem with:
`Mapnik does not support grayscale images for png`

I was building Mapnik 3.0.22 from source, and didn't realize that the Debian Stretch packages contain Mapnik 3.0.12. (building Mapnik from "master" build version 4.0.0 and caused a segfault with render_list)

Using the Debian version and rebuilding mod_tile and renderd from source made everything work!

@SomeoneElseOSM thanks for putting together such a great guide!
