### ISSUE TITLE
undefined reference to mapnik::freetype and other on centos 7

### ISSUE THREAD

**Issue by bain2236** [openstreetmap/mod_tile#178]
Hi

struggling to make mod_tile
I am following https://www.keisan.io/knowledgebase/centos-7-open-street-map-tile-server 
this guide.

This is my output when running make 
apologies for an image but i can't copy and paste from the vm I'm setting it up on
<img width="425" alt="mappingissue" src="https://user-images.githubusercontent.com/9283242/39200663-ac6f7f1c-47e4-11e8-83ec-9ea29e9ce1ac.png">

I literally have no idea where to even start debugging this?

**Comment by LobsterFestival** [comment]
@bain2236 Were youever able to find a resolution for this? I am also having the same issue!

**Comment by bain2236** [comment]
@LobsterFestival If I did I ran into further problems. I know that we eventually scrapped using a map server and basically got one from someone else but really unsure as it was 2 hours ago :) I hope you get over this

**Comment by xamanu** [comment]
Currently we don't have active support for CentOS, but we would like to get it back. Please refer to #230 to make it happen.
