### ISSUE TITLE
Preventing mod_tile rendering from blocking the serving of cached tiles?

### ISSUE THREAD

**Issue by Overv** [openstreetmap/mod_tile#182]
I've noticed that when all mod_tile workers are busy rendering tiles, no other tiles can be served at all, even if they're already in the cache. Is there a way to have mod_tile always serve previously rendered tiles instead of blocking on all requests when all workers are busy rendering?

**Comment by woodpeck** [comment]
What you describe must have another reason than you think.

When mod_tile finds a tile in the cache that is not old, it will deliver the tile without even talking to renderd, i.e. mod_tile at that point wouldn't even *know* whether renderd is under load or not. 

You could be seeing congestion on the Apache side (depending on which MPM you have and how it is configured) - try to request a harmless static page, does that work?

Or you could be seeing disk congestion so bad that mod_tile cannot even access the meta tile and extract the PNG from it. (unlikely!)

Or, you might have an old tile in the cache, and depending on the `ModTileRequestTimeout` setting, mod_tile might try to have the old tile rendered before handing out an old one. This would, however, not mean that old tiles are never delivered - they would be delievered after `ModTileRequestTimeout` seconds.

**Comment by Overv** [comment]
Thank you for your response, you may be right that the problem lies elsewhere then. I will investigate and get back to you.

**Comment by Overv** [comment]
Yep, you're right that it's behaving as you described, sorry for the bogus report.

**Comment by damiendevienne** [comment]
@Overv I am having the exact same impression that you describe in your initial post. How did you solve it finally? What was it? Cheers

**Comment by Overv** [comment]
@damiendevienne I didn't really solve it as such, I just inspected it properly this time by actually ensuring that all workers were busy rendering and requesting prerendered tiles and that worked fine.
