### ISSUE TITLE
Serve cache files permanently?

### ISSUE THREAD

**Issue by smisdocker** [openstreetmap/mod_tile#186]
I want to ask that is it possible that when mod_tile has prepared the tile and put inside the /var/lib/mod_tile folder for cache. Can we use that cache permanently? So mod_tile will not check for expiry and it will serve the tiles from /var/lib/mod_tile folder regardless of their age, but if tile does not get found in /var/lib/mod_tile folder then it will query the database and prepare the tile.

I am currently using ModTileBulkMode On, is it enough for my need?

Thanks.

**Comment by linsomniac** [comment]
In my testing, "ModTileBulkMode On" does seem to cause it to stop requesting re-rendering of tiles that have already been rendered.  In my situation, we periodically pull down the data from OSM and then deploy it to map tile servers.  That data is never updated in place, we would spin up a new box when we update OSM data.  A process goes through after the spin-up and renders all the tiles (we are covering a smallish geographic area).

With "ModTileBulkMode Off", going back and visiting these boxes after a 2 week vacation, in my testing environment, produced extremely slow page loads.  Calling my render script didn't produce any new tile files.  Once I enabled BulkMode, page loads were much faster.

**Comment by woodpeck** [comment]
Using ModTileBulkMode On will have a side effect, namely that render requests are sent with a lower priority. If *all* your requests have low priority then that's not too bad, but if the load on the machine should be a bit higher for some reason, it is possible that renderd will ignore low-priority requests. The desired effect can be more reliably reached by creating an empty file named "planet-import-complete" in /var/lib/mod_tile and giving it a modification timestamp earlier than the first tile (command line utility `touch -r` can be used for that).
