### ISSUE TITLE
Postgis Plugin: ERROR:  column "name" does not exist

### ISSUE THREAD

**Issue by maxdevaine** [openstreetmap/mod_tile#192]
Hello,
I don't know if is this problem on renderd side or somewhere else.
I builded my own OSM server with mod_tile. I used this howto :
https://wiki.openstreetmap.org/wiki/Debian/Stretch/FR:Installation

So, I used this :
Debian 9.6
Apache 2.4.25
Node.js 8.15 (from Node.js Debian repository)
carto 0.16.3 (installed via npm)
mod_tile + renderd compiled from git
mapnik 3.0.12 (Debian Stretch package)
osm2pgsql 0.92 (Debian Stretch package)
PostgreSQL 11 (from postgresql Debian repository)
OpenStreetMap Carto (from git)

All looks ok, 
"carto project.mml > style.xml" was sucessful without error
osm2pgsql map import was sucessful without error

but "renderd" give this error (if I try load web page with map overlay): 

`Jan  1 22:34:31 osm-ph renderd[3713]: DEBUG: DONE TILE default 9 248-255 152-159 in 0.040 seconds
Jan  1 22:34:31 osm-ph renderd[3713]: DEBUG: Sending render cmd(4 default 9/250/157) with protocol version 2 to fd 7
Jan  1 22:34:31 osm-ph renderd[3713]: DEBUG: Sending render cmd(4 default 9/252/159) with protocol version 2 to fd 11
Jan  1 22:34:31 osm-ph renderd[3713]: DEBUG: Sending render cmd(4 default 9/248/157) with protocol version 2 to fd 10
Jan  1 22:34:31 osm-ph renderd[3713]: DEBUG: Failed to read cmd on fd 7
Jan  1 22:34:31 osm-ph renderd[3713]: DEBUG: Connection 0, fd 7 closed, now 5 left
Jan  1 22:34:31 osm-ph renderd[3713]: DEBUG: Failed to read cmd on fd 11
Jan  1 22:34:31 osm-ph renderd[3713]: DEBUG: Connection 4, fd 11 closed, now 4 left
Jan  1 22:34:31 osm-ph renderd[3713]: DEBUG: Sending render cmd(4 default 9/249/157) with protocol version 2 to fd 13
Jan  1 22:34:31 osm-ph renderd[3713]: DEBUG: Failed to read cmd on fd 13
Jan  1 22:34:31 osm-ph renderd[3713]: DEBUG: Connection 2, fd 13 closed, now 3 left
Jan  1 22:34:31 osm-ph renderd[3713]: DEBUG: Sending render cmd(4 default 9/251/157) with protocol version 2 to fd 9
Jan  1 22:34:31 osm-ph renderd[3713]: DEBUG: Failed to read cmd on fd 9
Jan  1 22:34:31 osm-ph renderd[3713]: DEBUG: Connection 1, fd 9 closed, now 2 left
Jan  1 22:34:31 osm-ph renderd[3713]: DEBUG: Failed to read cmd on fd 10
Jan  1 22:34:31 osm-ph renderd[3713]: DEBUG: Connection 1, fd 10 closed, now 1 left
Jan  1 22:34:31 osm-ph renderd[3713]: ERROR: failed to render TILE default 9 240-247 160-167
Jan  1 22:34:31 osm-ph renderd[3713]:    reason: Postgis Plugin: ERROR:  column "name" does not exist#012LINE 1: SELECT ST_AsBinary("way") AS geom,"feature","name","way_pixe...#012                                                    ^#012in executeQuery Full sql was: 'SELECT ST_AsBinary("way") AS geom,"feature","name","way_pixels" FROM (SELECT#012    way, way_pixels,#012    COALESCE(wetland, landuse, "natural") AS feature#012  FROM (SELECT#012      way,#012      ('landuse_' || (CASE WHEN landuse IN ('forest', 'farmland', 'residential', 'commercial', 'retail', 'industrial', #012                                            'meadow', 'vineyard', 'orchard') THEN landuse ELSE NULL END)) AS landuse,#012      ('natural_' || (CASE WHEN "natural" IN ('wood', 'sand', 'scree', 'shingle', 'bare_rock', 'heath', 'grassland', 'scrub') THEN "natural" ELSE NULL END)) AS "natural",#012      ('wetland_' || (CASE WHEN "natural" IN ('wetland', 'mud') THEN (CASE WHEN "natural" IN ('mud') THEN "natural" ELSE tags->'wetland' END) ELSE NULL END)) AS wetland,#012      way_area/NULLIF(305.748::real*305.748::real,0) AS way_pixels,#012      way_area#012    FROM planet_osm_polygon#012    WHERE (landuse IN ('forest', 'farmland', 'residential', 'commercial', 'retail', 'industrial', 'meadow', 'vineyard', 'orchard')#012      OR "natural" IN ('wood', 'wetland', 'mud', 'sand', 'scree', 'shingle', 'bare_rock', 'heath', 'grassland', 'scrub'))#012      AND way_area > 0.01*305.748::real*305.748::real#012  ) AS features#012  ORDER BY way_area DESC, feature#012) AS landcover_low_zoom WHERE "way" && ST_SetSRID('BOX3D(-1291480.029907033 6848757.734355468,-587036.3772304694 7553201.387032032)'::box3d, 3857)'
Jan  1 22:34:31 osm-ph renderd[3713]: DEBUG: DONE TILE default 9 240-247 160-167 in 0.040 seconds
Jan  1 22:34:31 osm-ph renderd[3713]: DEBUG: Sending render cmd(4 default 9/246/160) with protocol version 2 to fd 8
Jan  1 22:34:31 osm-ph renderd[3713]: DEBUG: Failed to read cmd on fd 8
Jan  1 22:34:31 osm-ph renderd[3713]: DEBUG: Connection 0, fd 8 closed, now 0 left
`

So I think, that problem is in sql:
`Postgis Plugin: ERROR:  column "name" does not exist`

Do you know,  if is problem in renderd, or somewhere else? Maybe I made a mistake somewhere else, I don't know :-/

Thank you

**Comment by saltamocas** [comment]
Hi,
It look like a problem in the query:
To SELECT name in the first SELECT statement you must provide it from the sub SELECT and you don't select the column name in this sub select. In fact you have to select it also in the sub sub SELECT.
I can run the query with no error by correcting the sample in the log as shown above:
 SELECT ST_AsBinary("way") AS geom,"feature","name","way_pixels" 
	FROM (SELECT way, way_pixels, name, COALESCE(wetland, landuse, "natural") AS feature 
		  FROM (SELECT name, way, ('landuse_' || (CASE WHEN landuse IN ('forest', 'farmland', 'residential', 'commercial', 'retail', 'industrial', 'meadow', 'vineyard', 'orchard') THEN landuse ELSE NULL END)) AS landuse, ('natural_' || (CASE WHEN "natural" IN ('wood', 'sand', 'scree', 'shingle', 'bare_rock', 'heath', 'grassland', 'scrub') THEN "natural" ELSE NULL END)) AS "natural", ('wetland_' || (CASE WHEN "natural" IN ('wetland', 'mud') THEN (CASE WHEN "natural" IN ('mud') THEN "natural" ELSE tags->'wetland' END) ELSE NULL END)) AS wetland, way_area/NULLIF(305.748::real*305.748::real,0) AS way_pixels,way_area
		  	FROM planet_osm_polygon WHERE (landuse IN ('forest', 'farmland', 'residential', 'commercial', 'retail', 'industrial', 'meadow', 'vineyard', 'orchard') OR "natural" IN ('wood', 'wetland', 'mud', 'sand', 'scree', 'shingle', 'bare_rock', 'heath', 'grassland', 'scrub')) AND way_area > 0.01*305.748::real*305.748::real ) AS features ORDER BY way_area DESC, feature) AS landcover_low_zoom WHERE "way" && ST_SetSRID('BOX3D(-1291480.029907033 6848757.734355468,-587036.3772304694 7553201.387032032)'::box3d, 3857)

I hope it helps,
Luis

**Comment by saltamocas** [comment]
Don't bother with DEBUG messages, they are not really errors; receiving all those messages just mean that all the components are apparently ok (postgresql, renderd, apache, etc).
I forgot to emphasize the parts that are missing in the query:

SELECT ST_AsBinary("way") AS geom,"feature","name","way_pixels"
FROM (SELECT way, way_pixels, **name**, COALESCE(wetland, landuse, "natural") AS feature
FROM (SELECT **name**, way, ('landuse_' || (CASE WHEN landuse IN ('forest', 'farmland', 'residential', 'commercial', 'retail', 'industrial', 'meadow', 'vineyard', 'orchard') THEN landuse ELSE NULL END)) AS landuse

**Comment by pnorman** [comment]
This is a stylesheet error, not a mod_tile one.
