### ISSUE TITLE
debug: init_storage_backend: initialising file storage backend at: /var/lib/mod_tile

### ISSUE THREAD

**Issue by mixap** [openstreetmap/mod_tile#194]
Hello 
When i m ping url : http://10.10.21.38/osm_tiles/14/11705/6833.png its getting the apache's log appears the error. 

debug: init_storage_backend: initialising file storage backend at: /var/lib/mod_tile
debug: init_storage_backend: initialising file storage backend at: /var/lib/mod_tile

Please help me.

Thanks in advanced

Vinod

**Comment by julienfastre** [comment]
I do not know if you could find some help somewhere else.

Could you:

* check that the directory `/var/lib/mod_tile` does exist ;
* check the permission of the directory ;
* and compare the to the user executing renderd ;
