### ISSUE TITLE
Getting HTTP 408 in Apache2 Access Logs

### ISSUE THREAD

**Issue by Binternet** [openstreetmap/mod_tile#195]
I've been getting lots of lots of `408` HTTP codes:
`192.168.14.60 - - [26/Mar/2019:10:40:48 +0000] "-" 408 - "-" "-"`

I've tried changing `KeepAliveTimeout` but that doesn't create any change.

**Comment by SomeoneElseOSM** [comment]
Since it's unlikely to be a software problem, https://help.openstreetmap.org/ might be a better place to ask the question.  You'll need to provide a bit more information though - what are you doing to access tiles and what tiles are you accessing?

**Comment by Binternet** [comment]
ok i'll check there, thanks!
