### ISSUE TITLE
renderd-postgresql service fails

### ISSUE THREAD

**Issue by sephelps** [openstreetmap/mod_tile#197]
When enabling `renderd-postgresql` service (`# systemctl enable renderd-postgresql`) and rebooting, the service fails with `socket bind failed for: /var/run/renderd/renderd.sock` unless I manually create `/var/run/renderd` and restart the service.

**Comment by julienfastre** [comment]
You could ask for systemd to create the directory on system start. 

Add those statement in the `[service]` part of the file which should be located in `/etc/systemd/system/renderd.service`:

```
[Unit]
Description=Renderd
After=network.target auditd.service

[Service]
RuntimeDirectory=./renderd
RuntimeDirectoryMode=0755
```

Here is my full systemd service definition:

```
[Unit]
Description=Renderd
After=network.target auditd.service

[Service]
User=gis
Group=gis
Type=simple
RuntimeDirectory=./renderd
RuntimeDirectoryMode=0755
Restart=always
ExecStart=/usr/local/bin/renderd --foreground -c /etc/renderd.conf 
MemoryHigh=90G
MemoryMax=100G
```
