### ISSUE TITLE
Missing man page for renderd.conf 

### ISSUE THREAD

**Issue by rhabacker** [openstreetmap/mod_tile#199]
The man page for renderd mentions a man page for renderd.conf (see https://github.com/openstreetmap/mod_tile/blob/master/docs/renderd.8#L41), which is not installed.

The man page for renderd.conf should be generated and installed.

**Comment by Firefishy** [comment]
PRs welcome.

**Comment by gfiedler** [comment]
The specified manual section for configuration files is 5 and for system daemons is 8.

See `man man`.

**Comment by rhabacker** [comment]
This issue has been fixed with commit https://github.com/openstreetmap/mod_tile/commit/c683c5569ba2591f3e8d22d896a2338473c26e72.

**Comment by Faerbit** [comment]
AFAICT this is not fixed at all. Especially not in the linked commit. The man page for `renderd.conf` is still mentioned, while it doesn't seem to exist.

**Comment by hummeltech** [comment]
Yes, I believe you are correct @Faerbit. I will create a pull request for this, please give your feedback if you have the time. Thank you for the update!
