### ISSUE TITLE
renderd errors with osm.xml

### ISSUE THREAD

**Issue by cmyk** [openstreetmap/mod_tile#2]
When I start renderd -f, I get:

An error occurred while loading the map layer 'default': Could not create datasource for type: 'shape'  encountered during parsing of layer 'world' in Layer at line 4945 of '/home/postgres/osm-standard-style/mapnik-stylesheets/osm.xml'
renderd[16603]: An error occurred while loading the map layer 'default': Could not create datasource for type: 'shape'  encountered during parsing of layer 'world' in Layer at line 4945 of '/home/postgres/osm-standard-style/mapnik-stylesheets/osm.xml'
renderd[16603]: An error occurred while loading the map layer 'default': Could not create datasource for type: 'shape'  encountered during parsing of layer 'world' in Layer at line 4945 of '/home/postgres/osm-standard-style/mapnik-stylesheets/osm.xml'renderd[16603]: An error occurred while loading the map layer 'default': Could not create datasource for type: 'shape'  encountered during parsing of layer 'world' in Layer at line 4945 of '/home/postgres/osm-standard-style/mapnik-stylesheets/osm.xml'

This is line 4945:
    <Layer name="world" srs="+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +nadgrids=@null +no_defs +over">
        <StyleName>world</StyleName>
        <Datasource>
            <Parameter name="file">/home/postgres/osm-standard-style/mapnik-stylesheets/world_boundaries/shoreline_300.shp</Parameter>
            <Parameter name="type">shape</Parameter>
        </Datasource>
    </Layer>

These instructions are fubar: http://wiki.openstreetmap.org/wiki/HowTo_mod_tile
They create .// in urls.
I manually put .shp but it didn't make any difference.

**Comment by tasstwa** [comment]
I had the same issue, indeed changing renderd.conf setting of mapnik_plugin set to the output of ```mapnik-config --input-plugins``` got rid of the error message.

**Comment by DaviKaur** [comment]
An error occurred while loading the map layer 'default':

renderd[2917]: Loading parameterization function for renderd[2917]: Loading parameterization function for 

debug: init_storage_backend: initialising file storage backend at: /var/lib/mod_tile
renderd[2917]: Loading parameterization function for 
debug: init_storage_backend: initialising file storage backend at: /var/lib/mod_tile
renderd[2917]: Loading parameterization function for 
renderd[2917]: An error occurred while loading the map layer 'default': Could not load map file: File does not exist of '/home/jburgess/osm/svn.openstreetmap.org/applications/rendering/mapnik/osm-local.xml'
renderd[2917]: An error occurred while loading the map layer 'default': Could not load map file: File does not exist of '/home/jburgess/osm/svn.openstreetmap.org/applications/rendering/mapnik/osm-local.xml'
renderd[2917]: An error occurred while loading the map layer 'default': Could not load map file: File does not exist of '/home/jburgess/osm/svn.openstreetmap.org/applications/rendering/mapnik/osm-local.xml'renderd[2917]: An error occurred while loading the map layer 'default': Could not load map file: File does not exist of '/home/jburgess/osm/svn.openstreetmap.org/applications/rendering/mapnik/osm-local.xml'

What is the matter. Can you please help?

**Comment by SomeoneElseOSM** [comment]
@DaviKaur I'm not sure that's an actual bug as such - it just sounds like you've got something in your "renderd.conf" file (which will usually be somewhere like /usr/local/etc/renderd.conf) that shouldn't be there? 

Do the instructions at https://switch2osm.org/serving-tiles/manually-building-a-tile-server-14-04/ help?  That should explain what needs to point at what.

**Comment by DaviKaur** [comment]
On Wed, Feb 17, 2016 at 3:36 PM, SomeoneElseOSM
<notifications@github.com> wrote:
>
> @DaviKaur I'm not sure that's an actual bug as such - it just sounds like you've got something in your "renderd.conf" file (which will usually be somewhere like /usr/local/etc/renderd.conf) that shouldn't be there?


You were right. I solved the issue on next day. Sorry for a delay in
reply. Thank you so much for answering this mail. :-)


-- 
Thanks & Regards

Davinder Kaur
Blog: https://lifearoundkaur.wordpress.com/
         https://kaurdavinder.wordpress.com/
         https://github.com/DaviKaur

**Comment by sachinvelaga** [comment]
@DaviKaur What changes did u make?

**Comment by SomeoneElseOSM** [comment]
Just in case it helps anyone, the changes I made to it last time I set up a tile server are over at https://github.com/SomeoneElseOSM/mod_tile/commits/master/renderd.conf .

Obviously there are some settings in there that won't apply elsewhere - for example the osm.xml location, maxzoom and the number of threads.

**Comment by black-giser** [comment]
@tasstwa  I encounter this problem too,and wanna get rid of it. But I have no such a render,conf file in  any directory.I need your help and waiting for your reply.More thanks in advance.

**Comment by black-giser** [comment]
@springmeyer  According your reply,mapnik-config exited a default path string dynamically.Also when it point into an error path,we can set a relative path string manually.Is that true?

**Comment by black-giser** [comment]
@cmyk could you tell me your final solutions about this issue? I encountered the same problem and haven't solved it so far.Do you have any tips or thoughts about this?
