### ISSUE TITLE
Tiles no longer completely rendering correctly.

### ISSUE THREAD

**Issue by Kradenko** [openstreetmap/mod_tile#200]
Hi,

All of a sudden last night, without changing anything my two mapping servers have started mis-rendering tiles. This is what it looks like now.

![2019-11-30 (2)](https://user-images.githubusercontent.com/21176283/69896774-9c102480-134b-11ea-8a4c-99e001e13c35.png)

The servers were setup at different times. I also removed and recreated the ajt folder. The tiles do seem to render partially and they don't throw errors.

Any idea why it would do this?

**Comment by Kradenko** [comment]
So I have been doing some testing, I re-imported the data into the database and it now works again. What I do find strange is that it happened around the same time to two different databases on two different test machines.

Could the data somehow have expired in the postgresql server?

**Comment by SomeoneElseOSM** [comment]
> Could the data somehow have expired in the postgresql server?

I can't think of a way that that could have happened.  I've seen similar things when a machine ran out of memory and processes got killed, but that's unlikely to affect two machines identically.

Were you applying updates to the database via e.g. "openstreetmap-tiles-update-expire"?

**Comment by alexandervlpl** [comment]
Are you keeping the OSM databases updated with Osmosis or similar? I've seen daily updates break databases and cause rendering issues like this many times.

**Comment by SomeoneElseOSM** [comment]
As an aside, if you're using Osmosis please see https://help.openstreetmap.org/questions/74199/osmosis-failing-since-4-days and https://github.com/openstreetmap/osmosis/releases/tag/0.47.4 .  That issue wouldn't cause this problem though, and in the absence of any more information I doubt that there's anything anyone can do to investigate.
