### ISSUE TITLE
Version 0.5?

### ISSUE THREAD

**Issue by xamanu** [openstreetmap/mod_tile#216]
I would like to suggest we review the following Pull Requests, merge eventually, test properly and release a new version:

* https://github.com/openstreetmap/mod_tile/pull/202 - Move variables to prevent duplicates (Urgent bugfix)
* https://github.com/openstreetmap/mod_tile/pull/211 - Fix manpage for renderd (User facing)
* https://github.com/openstreetmap/mod_tile/pull/212 - Fix some spelling errors (Very low hanging fruit)
* https://github.com/openstreetmap/mod_tile/pull/213 - Adhere to FHS 3.0 and use daemon under /run (Keep up with the standards)

FYI, this step would be very helpful in order to get `libapache2-mod-tile` and `renderd` packaged up for Debian, thus make it available in its future releases and official software repositories. This would also bring it to the derivates (such as Ubuntu). If you are interested, [these are the patches](https://salsa.debian.org/debian-gis-team/libapache2-mod-tile/-/tree/ab076f33092f5108462d2e7bc26e096b93106c0b/debian/patches) we are currently applying on top of the current code base during built.

I really would like to be able to `apt install renderd`.

**Comment by johanhenselmans** [comment]
For FreeBSD, I'd like to propose 
https://github.com/openstreetmap/mod_tile/pull/116 - fixes for FreeBSD

if there would be a new version.

**Comment by xamanu** [comment]
Hi @johanhenselmans, thanks for your input and taking care mod_tile and renderd run well on FreeBSD. In case I became the new maintainer (#214), I'd glad to make sure it compiles well on FreeBSD and I hope to have your support in testing it there.

**Comment by johanhenselmans** [comment]
Sure, I'll make sure it will run without jumping through extra hoops on FreeBSD. 

Although I am no C++ guru, but with the help of some other *BSD people we can make it work properly again.

I might even contemplate to get it back into the ports collection again, provided there are some other people interested.

**Comment by Firefishy** [comment]
@jburgess777 Any chance you could review? Happy with the changes?

**Comment by xamanu** [comment]
All PRs have been merged, (thanks @jburgess777). I would suggest we test the current state and afterwards we can do a new release.
