### ISSUE TITLE
Debian Packages for version 0.5

### ISSUE THREAD

**Issue by xamanu** [openstreetmap/mod_tile#217]
The packages for Debian (and Ubuntu) are in [Debian's NEW queue](https://ftp-master.debian.org/new.html) and waiting for review, which may take a few months.

In the meantime it would be very nice if people could test them already thoroughly. For your convenience I set up a personal repository, which contain the following software:

* `libapache2-mod-tile`
* `renderd`
* `renderd-example-map`

To use this repository, add a corresponding line to your `/etc/apt/sources.list`:

* `deb https://deb.openbuildingmap.org/ bullseye main` (for Debian Testing, Ubuntu Focal and Ubuntu Groovy)
* `deb https://deb.openbuildingmap.org/ buster main` (for Debian Stable)

Then import the key that I used to sign the packages:

* `wget -O - https://deb.openbuildingmap.org/archive.key | sudo apt-key add - `
        
After that you can install the available software as any other package:

* $ `apt update`
* $ `apt install NAMEOFPACKAGE`

For example a simple

* $ `apt install renderd-example-map` should install all dependendies and give you a simple test map unter http://localhost/renderd-example-map (should look like [this temporary link](https://example.openbuildingmap.org/renderd-example-map/)).

Please test and find as many errors as possible (!), use any complex setup you are running! Now we can fix things easily and it would be good to get the maturest possible packages into Debian and Ubuntu for the next releases. Let me know if you find any problem, either here or reach me on IRC as `xamanu`.

Thank you!

**Comment by xamanu** [comment]
Packages have been accepted in the NEW queue and are available in `experimental` now:

* [libapache2-mod-tile](https://packages.debian.org/experimental/libapache2-mod-tile)
* [renderd](https://packages.debian.org/experimental/renderd)

Next step: Let's bring them into `sid` (`unstable`).

Has anybody have had a chance to test them already with the provided test repository?

**Comment by xamanu** [comment]
Quick heads-up: the packages are in Debian `unstable` and have passed successfully the [piuparts QA](https://piuparts.debian.org/sid/source/liba/libapache2-mod-tile.html). Thus they are expected to appear soon in `testing` and prepared to be included into the next versions of Debian and Ubuntu.

**Comment by xamanu** [comment]
The packages reached Debian Testing, which means, as long as there are no critical bugs we can expect them to get into the next stable versions of Debian and Ubuntu. Please help testing, so we can make sure it works for everybody when they are being published. Thanks.

**Comment by schaechtelchen** [comment]
> For example a simple
> 
>     * $ `apt install renderd-example-map` should install all dependendies and give you a simple test map unter http://localhost/renderd-example-map (should look like [this temporary link](https://example.openbuildingmap.org/renderd-example-map/)).

worked as expected on debian buster Linux v7 4.19.0-10-amd64 #1 SMP Debian 4.19.132-1 (2020-07-24) x86_64 GNU/Linux

What can I do more?

**Comment by xamanu** [comment]
You could install a full OSM stack, or if you have a special setup with custom tile styles it would be nice to know it all works.

**Comment by SomeoneElseOSM** [comment]
Thanks for this.  I've created https://switch2osm.org/serving-tiles/manually-building-a-tile-server-debian-11/ based on it.  Integrating it in this way makes the setup much easier.  Currently the "switch2osm" page is a standalone one not linked to the menus - I'll link it in when people have had a chance to test it.

**Comment by SomeoneElseOSM** [comment]
One question (and this may be me not understanding how logging on Debian normally works) is that if I do:

    sudo tail -f /var/log/syslog | grep " TILE "

I get

    Nov 15 21:52:44 debianvm65 renderd[17845]: renderd[17845]: DEBUG: START TILE s2o 13 4072-4079 2632-2639, new metatile
    Nov 15 21:52:44 debianvm65 renderd[17845]: DEBUG: START TILE s2o 13 4072-4079 2632-2639, new metatile
    Nov 15 21:53:06 debianvm65 renderd[17845]: renderd[17845]: DEBUG: DONE TILE s2o 13 4072-4079 2632-2639 in 22.003 seconds
    Nov 15 21:53:06 debianvm65 renderd[17845]: DEBUG: DONE TILE s2o 13 4072-4079 2632-2639 in 22.003 seconds

(every message appears twice).  This is after following https://switch2osm.org/serving-tiles/manually-building-a-tile-server-debian-11/ exactly, apart from loading a different .pbf, and no other changes.

**Comment by xamanu** [comment]
Thanks, @SomeoneElseOSM, it looks like Systemd is forwarding the log entries (a second time) to the syslog. Let me try to fix it.

**Comment by xamanu** [comment]
@SomeoneElseOSM, I created an issue to fix this in `mod_tile` (https://github.com/openstreetmap/mod_tile/issues/219), in the meantime the duplicated error can hopefully be avoided by setting `ForwardToSyslog=no` in the `/etc/systemd/journald.conf`.

**Comment by SomeoneElseOSM** [comment]
Thanks - more generally, "having more control over how mod_tile writes messages" has got to be a good thing, and it is something that other people have asked for elsewhere.

**Comment by xamanu** [comment]
Closing here, as the packages are included in Debian.
