### ISSUE TITLE
Affero GPL license

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/mod_tile#221]
The Readme states

> This program is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General Public License as published by the Free Software Foundation, either version 2 of the License, or (at your option) any later version.

It then proceeds to link to the regular GPL. I looked back in the history, and as far as I can see, mod_tile has always been GPL licensed, not AGPL.

**Comment by pnorman** [comment]
Note, a3f4230df6bc320b3b564ab20a29b57f787dbfe4 was the commit that introduced this bug.

cc @xamanu

**Comment by xamanu** [comment]
Thanks for spotting, @pnorman. Fixed.
