### ISSUE TITLE
Version 0.6

### ISSUE THREAD

**Issue by xamanu** [openstreetmap/mod_tile#227]
Considering to focus and wrap up a version 0.6, that may include:

* [x] Current `master` branch (includes mainly cleanups)
* [x] Code formatting and checks in CI: https://github.com/openstreetmap/mod_tile/pull/228
* [x] Fix for tests: https://github.com/openstreetmap/mod_tile/pull/129 and https://github.com/openstreetmap/mod_tile/issues/224
* [x] Drop of internal `iniparser`: https://github.com/openstreetmap/mod_tile/pull/226
* [x] Avoid timeout waiting for low priority queue request responses: https://github.com/openstreetmap/mod_tile/pull/205
* [x] Logging improvements: https://github.com/openstreetmap/mod_tile/pull/220
* [x] Include some details in error log message https://github.com/openstreetmap/mod_tile/issues/235
* [x] Prometheus endpoint: https://github.com/openstreetmap/mod_tile/pull/222
* [x] Make render_list reconnect if the renderd connection is lost: https://github.com/openstreetmap/mod_tile/pull/229
* [x] Replace select() by poll() https://github.com/openstreetmap/mod_tile/pull/239

Is there anything else, that you think we should make part of a 0.6 release?

**Comment by xamanu** [comment]
An testing version for 0.6 has been built and is available on [deb.openbuildingmap.org](https://deb.openbuildingmap.org). They include all mentioned enhancements and fixes as listed above, but not #220, yet, as I encountered a few things that I need to report back on the PR.

**Comment by xamanu** [comment]
A new release candidate for version 0.6 is availabe on [deb.openbuildingmap.org](https://deb.openbuildingmap.org/). Please test and let me know if there are any issues.

This is the changelog:

### Bug fixes:

* Addressed problems in threading tests
* Replaced select() by poll()
* Made render_list reconnect if the renderd connection is lost
* Made renderd send a response for low priority queue

### New features:

* Improved logging with using the GLib Logging Framework
* Added Prometheus logging system endpoint
* Overhauled README instructions, particularily for installation

### Clean-up

* Added Continous Integration pipeline for code format and build testing
* Consistent code formatting
* Clarified copyright statements and holders
* Moved several extras into `utils` directory
* Replaced the example map with a simpler setup
* Changed to use `/var/cache` instead of `/var/lib` for tiles
* Dropped:
  - Experimental Python implementation
  - Debian packaging (it's now being handled in [debian-gis-team/libapache2-mod-tile](https://salsa.debian.org/debian-gis-team/libapache2-mod-tile))
  - meta2tile
  - internal iniparser

**Comment by xamanu** [comment]
Quick heads-up: we are coming closer to the release, everything that has been planned for it, is in there now (on the `master` branch). I rerolled and made available test packages on [deb.openbuildingmap.org](https://deb.openbuildingmap.org/) and will leave them for roughly a week, if we don't find any issues with the current state, then we can do the relase.

If you can, please help testing - especially in a more complex setup you might be using. This is the best time to make sure it works for everybody before rolling it out into the repositories of Debian and Ubuntu. Thanks.!

**Comment by xamanu** [comment]
Let's give us this weekend for testing and beginning next week I'm planning to do the release, as long as no relevant bugs are reported. Please help testing, if you can. Thanks!

**Comment by xamanu** [comment]
Released. Thanks everybody involved.

**Comment by SomeoneElseOSM** [comment]
Is there any documentation associated with "Improved logging with using the GLib Logging Framework"?

The net effect that I'm seeing from that change is that no logs are all are written - presumably they are getting written (but not to the same log as before), or they're not getting written because they're turned off by default.  Either way, I'd expect that as part of this change some documentation would be produced that would explain to people how to deploy the new version with no functional change (same logs get written as before to same place with same verbosity).  Where is that?
