### ISSUE TITLE
Support for CentOS

### ISSUE THREAD

**Issue by xamanu** [openstreetmap/mod_tile#230]
This software is currently actively supported for Debian/Ubuntu. But it should also work on other Linux distributions without (m)any problems. And it used to work on CentOS. This issue is to add and maintain support for it again.

It probably just needs some documentation and some checks at compile time. If you are a somehow advanced user of CentOS and are willing to try it, test it, and contribute to bringing it back. Please comment here. Pull requests are also more than welcome.

**Comment by hummeltech** [comment]
I have created a pull request to at least partially address this:
#247

The main problem here is that `mapnik` & `mapnik-devel` are not available in any of the official repositories as well as several `mapnik`-dependent packages.

I.E. (at least two of the missing `mapnik` dependencies):
```
gdal-devel
proj-devel
```

Therefore, it will not be a very easy task to fix without packaging those dependency RPMs as well.

**Comment by xamanu** [comment]
This PR is very good! It's good to see that `mod_tile` still works on CentOS. But the extra repos to add the missing dependencies give me a bit of a headache when it comes to integrating it into our CI. Mainly because I would expect us to "maintain" that CI part. Or what is your assessment? Don't you expect that there are going to be sometimes changes in the pipeline that we have to respond to?

I wonder if it wouldn't be better to have a piece of documentation that people can follow to make it work under CentOS.

**Comment by hummeltech** [comment]
Yeah, that extra repository is maintained by myself and some of my colleagues, we are also building and packaging mod_tile, but it is not yet included in there. These packages are used in numerous environments, including some production ones, but I agree that it wouldn't be good to rely on it for an extended period of time, hence why I made it a secondary check and not a required one. If you would like to "reproduce" a repository like this, I believe we are working toward releasing the `.spec` files for these dependencies. That would also be a quasi documentary of the process we followed.

**Comment by SomeoneElseOSM** [comment]
@hummeltech https://switch2osm.org/serving-tiles/ is currently missing a "native CentOS / Redhat" page.  Is that something that'd be relatively easy to set up?  

(whether that'd be CentOS 7 or some other version I'd leave to people more familiar with where things are going with CentOS to say)

**Comment by hummeltech** [comment]
@SomeoneElseOSM I have created a `Build & Test` workflow for `Fedora 34`. The process is very similar to `CentOS` / `Red Hat` and might be of help in regard your query.
#248

**Comment by hummeltech** [comment]
@SomeoneElseOSM I have created a basic readme for building on CentOS 7.

https://github.com/hummeltech/mod_tile/blob/centos7/docs/building_on_centos_7.md

**Comment by xamanu** [comment]
Rerolled a PR to add CentOS in the CI and the documentation; both provided by @hummeltech - https://github.com/openstreetmap/mod_tile/pull/251

With these two things, I'd consider this issue to be solved.

**Comment by xamanu** [comment]
Addressed by #253.
