### ISSUE TITLE
Support for FreeBSD

### ISSUE THREAD

**Issue by xamanu** [openstreetmap/mod_tile#231]
This software is currently actively supported for Debian/Ubuntu. But it should also work on other Unix system without (m)any problems. And it used to work on FreeBSD. This issue is to add and maintain support for it again.

It probably just needs some documentation and some checks at compile time. If you are a somehow advanced user of FreeBSD and are willing to try it, test it, and contribute to bringing it back. Please comment here. Pull requests are also more than welcome.

**Comment by xamanu** [comment]
Friendly pinging @johanhenselmans and @leforestier

**Comment by xamanu** [comment]
We have been adding back support for Fedora #232 and CentOS #230, by:

* adding a CI pipeline (based on Github Actions) for each of the distributions
* adding simple step by step documentation on how to compile the sofwtare

For bringing back FeeBSD support to `mod_tile` and `renderd` we should accomplish similar things.

**Comment by thomersch** [comment]
This is currently blocked, because Mapnik doesn't build anymore on FreeBSD.

**Comment by schmied** [comment]
Mapnik builds fine on FreeBSD, I just did it. They removed it from ports a while ago. It sucked for years and was really annoying because of some trouble with a specific boost version.

**Comment by schmied** [comment]
Btw, I also just built mod_tile 0.6.1 and renderd with some very minor changes.

**Comment by thomersch** [comment]
Would you be willing to enlighten us or do you prefer to keep it to yourself? ;)

**Comment by schmied** [comment]
You are very welcome! :) If I got some time, I will fork and do pull requests, ok? A few lines should do the trick.

Sorry for beeing reserved, but I was not very happy all the time, with pull requests and forks sitting around for years (now outdated, mostly). Same with mapnik. But let's try again. See you soon and "Guten Rutsch"! :-)

**Comment by schmied** [comment]
See https://github.com/openstreetmap/mod_tile/pull/268

**Comment by xamanu** [comment]
Thanks @schmied for rerolling and improving the fixes.

**Comment by schmied** [comment]
Thank you guys!
