### ISSUE TITLE
Support for Fedora and Red Hat

### ISSUE THREAD

**Issue by xamanu** [openstreetmap/mod_tile#232]
This software is currently actively supported for Debian/Ubuntu. But it should also work on other Linux distributions without (m)any problems. This issue is to add and maintain support for Fedora and Red Hat.

It probably just needs some documentation and some checks at compile time. If you are a somehow advanced user of Fedora or Red Hat and are willing to try it, test it, and contribute to making it happen. Please comment here. Pull requests are also more than welcome.

**Comment by hummeltech** [comment]
@xamanu Since Fedora's package repositories include all required build dependencies for `mod_tile`, I have taken my CentOS pull request and modified it to work with Fedora 34:
#248

**Comment by xamanu** [comment]
This is great. I also extracted some simple documentation out of it and proposed it in the PR https://github.com/openstreetmap/mod_tile/pull/252.

With CI and instruction on how to compile on Fedora, we can consider to have back support for this distribution, and close this issue considering it done. Of course, if there is anybody out there, who wants to package it for Fedora, that would be always welcome.
