### ISSUE TITLE
ERROR: Module tile does not exist!

### ISSUE THREAD

**Issue by molandim** [openstreetmap/mod_tile#241]
Hi, I am trying to build a docker image following  the read me instructions, but at the end when I run `a2enmod tile` the output is `ERROR: Module tile does not exist!`

The built is bases on debian: 10 and the command `./autogen.sh && ./configure && make && make install && make install-mod_tile` have ran with no erros.

Here is the libraries I have installed

```
apt-get update && \
    apt-get install -y \
    libboost-all-dev \
    git \
    tar \
    unzip \
    wget \
    bzip2 \
    build-essential \
    autoconf \
    apache2 \
    apache2-dev \
    libgdal-dev \
    libcairo2-dev \
    libcurl4-gnutls-dev \
    libiniparser-dev \
    libmapnik-dev \
    npm
```

**Comment by pnorman** [comment]
a2enmod is a debian-specific thing. You need to load the module with the standard `LoadModule` method.

**Comment by stephankn** [comment]
the packaging for Debian was removed a while ago from this repository. You could use relatively recent modules from Debian. 
If you compile yourself, the module is created here: mod_tile/src/.libs/mod_tile.so

You can copy this module to your image, for example when using multi-staged build on docker, so you don't have all the compilers on your production image.

Store it in /usr/lib/apache2/modules/mod_tile.so

If you want to you a2enmod, you need a configuration file in /etc/apache2/mods-available. This is the file content before Debian packaging had been removed:
https://github.com/openstreetmap/mod_tile/blob/bb1782300d4b7d0ea653dca9ee4ed3ae1e813881/debian/tile.load

**Comment by stephankn** [comment]
the Configuration section of the README is a bit misleading.
https://github.com/openstreetmap/mod_tile#configuration

It assumes that you have installed the software from packages, which would place all the configuration files in the right location so Debian helper script can be used.

**Comment by molandim** [comment]
Thanks a lot for the quick response!
