### ISSUE TITLE
Module tile does not exist! #241

### ISSUE THREAD

**Issue by molandim** [openstreetmap/mod_tile#243]
Sorry to reopen a ticket, but in the #241 the explanation, if I got it right, was because this module is not installed with Debian. However I started another docker, this time using Ubuntu : 20.04 and again the same error. 

**ERROR: Module tile does not exist!**

This is my dockerfile

```
FROM ubuntu:20.04
ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update && \
    apt-get install -y \
    libboost-all-dev \
    git \
    tar \
    unzip \
    wget \
    bzip2 \
    build-essential \
    autoconf \
    apache2 \
    apache2-dev \
    libgdal-dev \
    libcairo2-dev \
    libcurl4-gnutls-dev \
    libiniparser-dev \
    libmapnik

```

**Comment by pnorman** [comment]
What's your apache config?

**Comment by xamanu** [comment]
I'd suggest you to use the packaged versions available in:

* Debian 11 (Bullseye) - to be released as stable within a few days.
* Ubuntu hirsute (21.04)

or later.

A simple `apt install libapache2-mod-tile renderd` should set it up for you.

**Comment by DaanDeJong2001** [comment]
sorry that my explanation is still not clear. If you do a manual build, then it is your own (manual) responsibility to place all files in the correct locations. Especially if you want to use Debian (Ubuntu is a Debian flavor) tools, you have to create all configuration files and place all of them at the right location.

The instructions on the "configuration" section relate to steps after you installed the deb packages (Debian/Ubuntu).
Unless you are actively developing on the module, it is likely that a module coming with your distribution is a better choice than building yourself.

**Comment by xamanu** [comment]
For reference, [this is a Dockerfile I'm using with the packages](https://git.gfz-potsdam.de/dynamicexposure/server-components/containers/docker-obm-tiles-raster/-/blob/master/Dockerfile), and it works quite fine.

**Comment by molandim** [comment]
All the configs I have copied from this repository  examples/config.


I am not trying to do any fancy, I am just trying to follow the readme instructions and make it run

**Comment by xamanu** [comment]
Maybe it is worth to add, that switch2osm has [some great tutorials](https://switch2osm.org/serving-tiles/manually-building-a-tile-server-20-04-lts/) on how to set up the software for older systems. But again, I recommend using the packaged version if you just want to run and not develop for it.

**Comment by xamanu** [comment]
@molandim can this issue be closed?

**Comment by xamanu** [comment]
Our CI pipeline runs on Ubuntu 20.04 (focal) and compiles and runs `mod_tile` well. Maybe it helps you to read the [speudo coded instructions](https://github.com/openstreetmap/mod_tile/blob/master/.github/workflows/github-actions.yml).
