### ISSUE TITLE
License & copyright changed for catch.hpp & daemon_compat.c 

### ISSUE THREAD

**Issue by sebastic** [openstreetmap/mod_tile#255]
Commit d706d96020658e449eba312aea75a544f9b5c2a3 changed the license and copyright for `catch.hpp` & `daemon_compat.c` incorrectly. These files are not part of the mod_tile codebase and have external origins.

The changes to these two files should be reverted.

**Comment by xamanu** [comment]
Many thanks for catching that, @sebastic! 032d90d1300a4c1d61687b61d047745b91fb99d0 reverted this.
