### ISSUE TITLE
Problems with CI pipeline - `uses:` keyword is not currently supported.

### ISSUE THREAD

**Issue by xamanu** [openstreetmap/mod_tile#256]
We are facing issues with the CI pipeline, based on Github Actions. They fail with this error:

```
Error: `uses:` keyword is not currently supported.
```

We use `uses:` in our github actions definition. It worked before and is [part of the official documentation](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepsuses). @hummeltech, by chance do you know what is going on?

**Comment by hummeltech** [comment]
Hello @xamanu, yes I looked into this and it appears that this functionality was removed (temporarily I hope.)

See here:
https://github.com/actions/runner/pull/1222
And the code addition in question here:
https://github.com/actions/runner/commit/4e95d0d6ad46e454749cc5d69a7072df34a8e12f#diff-5b282ef924f268139b4015eb491825d3e35bfa6cbe46962e3bef3bd8fa05dfccR431

**Comment by hummeltech** [comment]
I'm not exactly sure why (I didn't read in too carefully) but I assume it has to do with how outputs are handled in nested actions.
