### ISSUE TITLE
mod_tile compiler issue in arm processor 

### ISSUE THREAD

**Issue by Manumur** [openstreetmap/mod_tile#261]
Hi all,
I have faced mod_tile  compiler issue in ubuntu-20.04 arm processor ,is there any system compatibility issue in mod_tile compile?
Note :my server hosting in aws ubuntu 20.04 lts with arm processor

**Comment by xamanu** [comment]
There are no known issues neither with Ubuntu 20.04 nor with arm64 architecture. We actually build `mod_tile` in the continous integration with Ubuntu 20.04, and the official package builds for Debian (11) and Ubuntu (from 20.10 and later) have proper ARM builds as well.

Please provide more @Manumur and @jisss, can you give more information and description on what your problems are?

**Comment by xamanu** [comment]
Closed because of inactivity.
