### ISSUE TITLE
libapache2-mod-tile and renderd installation issue 

### ISSUE THREAD

**Issue by jisss** [openstreetmap/mod_tile#262]
hi,i have tried to install osm mapserver on ubuntu 20.04 arm server.but at the installation of libapache2-mod-tile renderd showed error unable to connect.snap install showedd no library support.
does anyone know about this? does ubuntu 20.04 arm architecture support apache2 and renderd?

**Comment by xamanu** [comment]
This sounds like a duplicate to #261. @jisss, please provide more details there. Thanks!

**Comment by jisss** [comment]
error unable to connect error showed,when i tried to install libapache2-mod-tile  and 
renderd
