### ISSUE TITLE
showed error in rendering

### ISSUE THREAD

**Issue by jisss** [openstreetmap/mod_tile#264]
osm server configuration,In renerding step i got the error"rendering failed with command 4 pausing"
after that i checked status of renderd by using the command sudo journalctl -eu renderd
it showed 
An error occurred while loading the map layer 'default': Postgis Plugin: could not connect to server: No such file or di>
                                                       Is the server running locally and accepting
                                                       connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
                                               Connection string: ' dbname=gis connect_timeout=4'
                                                 encountered during parsing of layer 'landcover-low-zoom' in Layer at line 819 of '/home/osm/openstreetmap-carto/style.xml
anybody know about issue and how to solve it?

**Comment by xamanu** [comment]
This doesn't seem to be an issue particularly with arm architecture. `mod_tile` needs a set of well configured programs working together to provide OpenStreetMap tiles. It seems your database is not present or properly configured. Have you seen [this tutorial](https://switch2osm.org/serving-tiles/manually-building-a-tile-server-20-04-lts/)? This should give you a good start and understanding of the pieces involved.

**Comment by jisss** [comment]
hi used this tutorial for installation https://www.linuxbabe.com/ubuntu/openstreetmap-tile-server-ubuntu-20-04-osm
