### ISSUE TITLE
CI error with CentOS after switching to geopackage in example map

### ISSUE THREAD

**Issue by xamanu** [openstreetmap/mod_tile#269]
Somehow the CI started failing for CentOS after switching to the open geopackage format for the input of the example map with this commit: https://github.com/openstreetmap/mod_tile/commit/7e81d950d14017055b203b1da40175dce2aa54ea

I'm not running CentOS myself and would like to ask @hummeltech for some help to look into the logs to check what is the problem here. Many thanks!

**Comment by xamanu** [comment]
The logs on the mentioned commit doesn't seem to be available anymore (but in the more recent commits they are [the same](https://github.com/openstreetmap/mod_tile/runs/4731805839?check_suite_focus=true). Anyway, all compilation went fine until the point of testing `mod_tile`:

```
Run while ! curl --fail http://localhost:8081/tiles/renderd-example/9/297/191.png &> /dev/null
103
+ curl --fail http://localhost:8081/tiles/renderd-example/9/297/191.png
104
+ sleep 5
+ curl --fail http://localhost:8081/tiles/renderd-example/9/297/191.png
106
+ sleep 5
...
````

It seems that the tiles aren't reachable anymore.

**Comment by pnorman** [comment]
> It seems that the tiles aren't reachable anymore.

Anything in the renderd/mod_tile logs?

**Comment by xamanu** [comment]
[Temporarily disabled CentOS builds in CI](https://github.com/openstreetmap/mod_tile/commit/ad0439ecb1be6a5229bc91addfde2fb864bda07d), until somebody with love for CentOS wants to debug it and send a fix.

**Comment by hummeltech** [comment]
Hey @xamanu, it looks like the original `Shapefile`=>`GeoPackage` conversion caused this failure, I reconverted it with `ogr2ogr` and that seems to have fixed it (it tested fine with many Linux distributions.)

**Comment by hummeltech** [comment]
@xamanu I think this can be closed.
