### ISSUE TITLE
Slow rendering

### ISSUE THREAD

**Issue by Mahabarata** [openstreetmap/mod_tile#294]
Hi,

4 days ago I improved a very simple wetland multipolygon: an outer closed way with a water inner area. All the elements (the 2 ways and the relation) already existed, I didn't change geometry, I didn't change the ways, I just put back some tags on the relation.

* at zoom 18, rendering was updated in a few minutes : https://www.openstreetmap.org/relation/11143425#map=18/55.86530/36.68869
* at zoom 17, rendering is still outdated 4 days after my changeset: https://www.openstreetmap.org/relation/11143425#map=17/55.86530/36.68869
* same thing at zoom 16 to 14
* but rendering is ok at zoom 13, 12 and 11 (at 10 or smaller zoom the area is almost invisible on my screen so I don't know).

Same thing with this big multipolygon:
* at zoom 13 all is ok https://www.openstreetmap.org/relation/11979428#map=13/50.3531/44.1880
* at zoom 14 a part is outdated https://www.openstreetmap.org/relation/11979428#map=14/50.3502/44.1449
* worse at zoom 15 https://www.openstreetmap.org/relation/11979428#map=15/50.3431/44.1279
* very bad at zoom 17 https://www.openstreetmap.org/relation/11979428#map=17/50.34552/44.12372 (if you move the map at this zoom you will see that the outdated part is more than half the area of the entire multipolygon)
* but better at zoom 18 https://www.openstreetmap.org/relation/11979428#map=18/50.34547/44.12408

Why it doesn't work at highest zooms but work at lowest zooms ? A few months ago it was the contrary, renderings at highest zooms were updated quite quickly and we needed a few days at lowest zooms to see the updated renderings: it was better in my opinion, 4 days and no rendering at zoom 17 for the first relation looks strange, no ?

Best regards

**Comment by xamanu** [comment]
Please ask OpenStreetMap related questions of this kind in the [new forum](https://community.openstreetmap.org/). This here repository is to discuss around software development of `mod_tile` and `renderd`.

**Comment by Mahabarata** [comment]
Ok, thanks.
