### ISSUE TITLE
Unable to generate webp tiles

### ISSUE THREAD

**Issue by julienrf** [openstreetmap/mod_tile#301]
I saw that there is `TYPE` setting but it seems only `png image/png` is supported. Is it possible to produce webp files? I’ve observed that webp files are less than half the size of their png equivalent for a very small loss of quality:

~~~ text
$ ls -hl
-rw-rw-r-- 1 julien julien 42K Dec 10 21:19 biella.png
-rw-rw-r-- 1 julien julien 16K Dec 10 21:50 biella.webp
~~~

biella.png:

![biella](https://user-images.githubusercontent.com/332812/206875839-99f96e95-8af9-405c-b244-cf05ebd3324f.png)

biella.webp:

![Screenshot from 2022-12-10 22-28-07](https://user-images.githubusercontent.com/332812/206875894-a157f327-c406-454d-a4c7-cfb76ae74a8b.png)

**Comment by hummeltech** [comment]
@julienrf There is [a pull request](https://github.com/openstreetmap/mod_tile/pull/191) which allows this to be done by adding `outputFormat` to `TYPE` so setting `TYPE` to `webp image/webp webp` would do what you are asking about. I have rebased it on the current codebase and left a [comment here](https://github.com/openstreetmap/mod_tile/pull/191#issuecomment-1452425876).

**Comment by julienrf** [comment]
That’s fantastic, thank you @hummeltech for helping with that!
