### ISSUE TITLE
Add support for mapnik falling back to pkg-config if mapnik-config is not present

### ISSUE THREAD

**Issue by nmaludy** [openstreetmap/mod_tile#303]
Whenever the Mapnik makes a new release, the build system supports CMake which doesn't  generate the `mapnik-config` tool:  https://github.com/mapnik/mapnik/issues/4330

It would be great if mod_tile could fallback to using pkg-config to find the library if `mapnik-config` is not present.

**Comment by hummeltech** [comment]
Hey @nmaludy, great thinking!

I was working on resolving this issue and #304 [here](https://github.com/openstreetmap/mod_tile/compare/master...hummeltech:mod_tile:Mapnik4), you can see [it passing in GitHub Actions](https://github.com/hummeltech/mod_tile/actions/runs/4145443260/jobs/7169805677) as well.

**Comment by nmaludy** [comment]
Awesome, great work!
