### ISSUE TITLE
Mapnik master moved mapnik/box2d.hpp to mapnik/geometry/box2d.hpp

### ISSUE THREAD

**Issue by nmaludy** [openstreetmap/mod_tile#304]
Master branch of mapnik moved mapnik/box2d.hpp to mapnik/geometry/box2d.hpp causing issues building `src/gen_tile_test.cpp`

Probably need to add some fixes to the #ifdef block here: https://github.com/openstreetmap/mod_tile/blob/master/src/gen_tile_test.cpp#L50-L58 whenever they release the next version

**Comment by hummeltech** [comment]
Awesome, I pushed up [a pull request](https://github.com/openstreetmap/mod_tile/pull/305) so that both `Mapnik >= 4` & `Mapnik < 4` will be tested.
