### ISSUE TITLE
send error: Inappropriate ioctl for device

### ISSUE THREAD

**Issue by littlTom** [openstreetmap/mod_tile#314]
![image](https://user-images.githubusercontent.com/118588293/224267604-aa57c6d6-8860-448a-9cd1-00f964f513b4.png)
How should I solve this problem? Thanks a lot!

**Comment by hummeltech** [comment]
We'll probably need to see your `renderd.conf` file, the first 50 lines or so of the `log output` and the the command you used to start up `renderd` in order to provide any help.

**Comment by littlTom** [comment]
![image](https://user-images.githubusercontent.com/118588293/224458234-50e0cfda-0bb7-46cb-a418-17e4c795de9f.png)

**Comment by littlTom** [comment]
![image](https://user-images.githubusercontent.com/118588293/224458302-0fd147fe-a5ac-4c99-82a7-90c0a772f221.png)

**Comment by littlTom** [comment]
> We'll probably need to see your file, the first 50 lines or so of the and the the command you used to start up in order to provide any help.`renderd.conf``log output``renderd`

![image](https://user-images.githubusercontent.com/118588293/224458541-36d0f0da-d872-4332-a947-86b391303606.png)

**Comment by littlTom** [comment]
> We'll probably need to see your file, the first 50 lines or so of the and the the command you used to start up in order to provide any help.`renderd.conf``log output``renderd`

![image](https://user-images.githubusercontent.com/118588293/224458740-62aa59ee-8aff-434c-a905-f47281ebf10d.png)

**Comment by hummeltech** [comment]
> > We'll probably need to see your file, the first 50 lines or so of the and the the command you used to start up in order to provide any help.`` renderd.conf``log output``renderd ``
> 
> ![image](https://user-images.githubusercontent.com/118588293/224458541-36d0f0da-d872-4332-a947-86b391303606.png)

It looks like the `postgres` user doesn't have permissions to write into the `/run/renderd` directory and/or it doesn't exist. First check if that directory (`/run/renderd`) exists and is writable.
```shell
$ sudo -u postgres ls -al /run/renderd
ls: cannot access '/run/renderd': No such file or directory
```
If not, you'll need to create it:
```shell
$ sudo mkdir /run/renderd
```
Then, whether it existed or not, grant `postgres` write permissions to it:
```shell
$ sudo chown postgres:postgres /run/renderd
```

You'll probably have a similar issue with the `tile_dir`, so do the same thing for `/var/cache/renderd/tiles`:
```shell
$ sudo -u postgres ls -al /var/cache/renderd/tiles
ls: cannot access '/var/cache/renderd/tiles': No such file or directory
$ sudo mkdir -p /var/cache/renderd/tiles
$ sudo chown postgres:postgres /var/cache/renderd/tiles
```

**Comment by littlTom** [comment]
Thanks for your help! I have solved this problem!
