### ISSUE TITLE
Maintainer change?

### ISSUE THREAD

**Issue by xamanu** [openstreetmap/mod_tile#327]
Hi there,

following up on https://github.com/openstreetmap/mod_tile/issues/214, where I expressed that I would take the maintainer role until there is another more suitable candidate.

IMHO, @hummeltech has shown dedication and great, reliable work over the last months. I feel I am slowing down the process here as the gatekeeper and @hummeltech has much more knowledge than I have. So I am wondering whether @hummeltech would like to become a maintainer and others are fine with it. I would still be around but focus on the Debian/Ubuntu packaging.

Cheers!

**Comment by hummeltech** [comment]
Hello, I would be more than happy to take on this duty, it would be an honor.

**Comment by xamanu** [comment]
Thanks @hummeltech. Any chance to get them permissions, @pnorman, @tomhughes?

**Comment by pnorman** [comment]
I have no access to do so.

**Comment by tomhughes** [comment]
@jburgess777 is the one with admin powers here though it doesn't look like he's done anything for a few years. 

@apmon also had admin powers but hasn't been seen here for like 10 years so I've just removed him.

I've added @hummeltech as a maintainer but should we also bump @xamanu up to admin?

**Comment by xamanu** [comment]
Many thanks! No need to make me an admin.
