### ISSUE TITLE
CPU/IO not fully utilized when under heavy load

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/mod_tile#333]
The OSMF got a new tile server, and in scaling it up, I've observed some odd behavior.

When I throw a heavy load onto the server, a queue builds up. This is semi-expected, but the average time per tile, as computed by `TimeRenderedZoom/ZoomRendered` becomes approximately 4.2 seconds. Normally it ranges from <1s for high zooms to 5-10s for zoom 13.

This can be seen in [prometheus](https://prometheus.openstreetmap.org/d/wyyzhZKMk/tile-rendering?orgId=1&from=1694715282056&to=1694716812056&var-instance=piasa)

![image](https://github.com/openstreetmap/mod_tile/assets/1190866/dd46f608-8361-491d-bc2b-912549f47969)

With a bit of work I was able to see this with a [partially filled queue](https://prometheus.openstreetmap.org/d/wyyzhZKMk/tile-rendering?orgId=1&from=1694720569970&to=1694721594263&var-instance=piasa)
 although in this case it's just the high zooms. 

![image](https://github.com/openstreetmap/mod_tile/assets/1190866/2437898e-c33c-4814-9bc3-95019c2d5fd6)

Looking at the code that produces the render time and number of tiles stats, they're set in https://github.com/openstreetmap/mod_tile/blob/24a5752d93bb04477bfd96255f0d4f0fbb9e4867/src/request_queue.c#L371-L401 with render_time coming from https://github.com/openstreetmap/mod_tile/blob/24a5752d93bb04477bfd96255f0d4f0fbb9e4867/src/gen_tile.cpp#L505, which is essentially the call time of `maps[i].store->tile_stat` and `render`, in ms.

I'm somewhat stumped here, but a few thoughts are
- this is limiting render capacity well below what it should be
- the machine has idle capacity throughout, particularly CPU
- why 4.2s?
- how does the average zoom 13 time per tile *decrease*?

**Comment by pnorman** [comment]
Tied in with this is the fact it's starting to queue tiles when CPU is under 50%, while num_threads is approximately equal to the number of hardware threads.

**Comment by pnorman** [comment]
In an attempt to isolate what's going on, I left the load normal and used render_list to render z17 tiles. It started off behaving as above, with 4 seconds per tile rendered and CPU usage <50%. Then without changing anything, throughput spiked up, time/tile went down, and CPU usage went to 100%.

![image](https://github.com/openstreetmap/mod_tile/assets/1190866/a278a4cb-0f60-4828-a30b-126029eac01a)

render_list was with `-n 80` and num_threads is 120, and the machine has 80 hardware threads

In an effort to reduce the problem down, I shut off apache2/mod_tile and tried render_list with an assortment of -n. Increasing -n doesn't increase throughput or CPU usage, except that sometimes it goes from not running at capacity to generating more tiles and being CPU bottlenecked.

I'm wondering, could some kind of lock be limiting how many requests per second it can deal with? But that wouldn't explain the bursts of good performance.

**Comment by pnorman** [comment]
![image](https://github.com/openstreetmap/mod_tile/assets/1190866/1e18712f-f9d6-4f71-9c69-596fe5876786)
![image](https://github.com/openstreetmap/mod_tile/assets/1190866/9fba6891-7ca7-4068-8a3d-2ff92f125d44)

I didn't change anything, but sometimes it goes from 28 tiles/second to 92 tiles/second

**Comment by pnorman** [comment]
I wonder if this is related to https://github.com/openstreetmap/mod_tile/blob/24a5752d93bb04477bfd96255f0d4f0fbb9e4867/src/render_submit_queue.c#L207-L213

This limits the queue size to 32, which might be too low modern hardware. But as far as I can tell, this file is only included by the render_* helper programs.

There are also a bunch of constants for mod_tile that might not make sense on modern hardware: https://github.com/openstreetmap/mod_tile/blob/24a5752d93bb04477bfd96255f0d4f0fbb9e4867/includes/mod_tile.h#L24-L33, or the queue size constants https://github.com/openstreetmap/mod_tile/blob/24a5752d93bb04477bfd96255f0d4f0fbb9e4867/includes/render_config.h#L112-L114

**Comment by pnorman** [comment]
We did some debugging on piasa today.

Increasing QMAX to 256 had no impact. Increasing REQ_LIMIT and DIRTY_LIMIT to 256 and 8000 had no impact. The following patchset had no impact
[download.compton.nu_tmp_queue-concurrency.patch.txt](https://github.com/openstreetmap/mod_tile/files/12652297/download.compton.nu_tmp_queue-concurrency.patch.txt). 
The testing with the patchset and with the REQ_LIMIT and DIRTY_LIMIT changes was not *identical* to the previous testing, because it was built with march=native.

Running for longer established that the spikes of working at 100% happen every 8.4 minutes. In tests on the 18th, they were happening 7.25 minutes, and on the 15th, every 7.5 minutes.

**Comment by pnorman** [comment]
I attached gdb and got some useful information with a backtrace of all the threads. Of the 81 threads, 61 of them were at `futex_wait` within `mapnik::freetype_engine::create_face_impl`, inside the rendering of an image. 9 threads were doing other Mapnik work, 4 were in `__pthread_cond_wait_common` with no Mapnik calls, 2 were within PQgetResult, and the last two were overall renderd threads.

**Comment by hummeltech** [comment]
Hi @pnorman, I'm seeing a pull request which seems to address this issue, #334. As well as another related pull request, #335. Let me know if you have yet had a chance to try out those changes and if they have resolved this issue for you so that this issue can be closed out (or not.) I am currently planning to get a new release put together soon and so just wanted to gather some information and close some issues & pull requests out beforehand.

**Comment by pnorman** [comment]
Ya, we're seeing much better CPU usage now. #334 was the big change, #335 helped minorly.
