### ISSUE TITLE
Log spam at startup/reload

### ISSUE THREAD

**Issue by tomhughes** [openstreetmap/mod_tile#43]
Every time apache is started or reloaded an informational message is logged to the console:

```
[Tue Aug 13 08:10:59 2013] [notice] Loading tile config default at /default/ for zooms 0 - 19 from tile directory /srv/tile.openstreetmap.org/tiles with extension .png and mime type image/png
```

**Comment by xamanu** [comment]
Is this still an issue with the latest `master` or the version 0.6 release candidate? Tried it here and I don't get any of this message.

**Comment by tomhughes** [comment]
It seems not although I'm not sure why given it's still in the code.

**Comment by xamanu** [comment]
ok, thanks, closing here. Please reopen if one spots this error again and can reproduce it.
