### ISSUE TITLE
Dirty tiles cached for 7 days

### ISSUE THREAD

**Issue by nrenner** [openstreetmap/mod_tile#441]
*See also [operations#1096](https://github.com/openstreetmap/operations/issues/1096) for examples and trying to infer from indirect hints.*

From just looking at the code¹, I guess `state` in `add_expiry` is actually `tileVeryOld`² and not `tileOld` for dirty tiles:

https://github.com/openstreetmap/mod_tile/blob/1f81434203d4f6977f8458a7ea42f31523cfa0e0/src/mod_tile.c#L526-L527

Determined in `tile_state`:

https://github.com/openstreetmap/mod_tile/blob/1f81434203d4f6977f8458a7ea42f31523cfa0e0/src/mod_tile.c#L442-L448

Assuming the default³ of 1 year for `scfg->veryold_threshold`, 20-year-old expired tiles will be older and therefore `tileVeryOld`.

So, dirty tiles would not get a low maxAge as originally intended. Instead, maxAge would be derived from modified time (-20 years) and  clamped to `ModTileCacheDurationMax`, resulting in a `Cache-Control: max-age=604800`.

¹ not entirely sure if this is the code actually used for OSMF render servers and in what version; permalinks for current master
² `tileVeryOld` [was introduced](https://github.com/openstreetmap/mod_tile/commit/1b4c56d8eda631179b5d03e8472e981425eb1a5f#diff-531f2ce0748b97527d6baf14e5c0dec0db585fbf1bf9eec14511a34eaf797575L359-R371) 11 years ago, apperently without adjusting the `add_expiry` code
³ [searching](https://github.com/search?q=repo%3Aopenstreetmap%2Fchef%20ModTileVeryOldThreshold&type=code) for `ModTileVeryOldThreshold` in chef does not find any overriding config, default should be one year:
  - https://github.com/openstreetmap/mod_tile/blob/1f81434203d4f6977f8458a7ea42f31523cfa0e0/includes/render_config.h#L47-L49

**Comment by hummeltech** [comment]
Thank you @nrenner, I assume you are suggesting changing this:
https://github.com/openstreetmap/mod_tile/blob/1f81434203d4f6977f8458a7ea42f31523cfa0e0/src/mod_tile.c#L527

To something like this:
```C++
		if (state == tileOld || state == tileVeryOld) {
```

Otherwise, please feel free to offer up a suggested fix for your issue. I am still not entirely clear about what your proposed solution would be.

**Comment by nrenner** [comment]
The same issue applies to `tile_handler_status`:

https://github.com/openstreetmap/mod_tile/blob/7e81d950d14017055b203b1da40175dce2aa54ea/src/mod_tile.c#L1164

The tile `/status` call always says "Tile is clean", even though the tile is clearly expired by an old date, e.g.:
`Tile is clean. Last rendered at Fri Jun 11 15:54:33 2004`
https://ysera.openstreetmap.org/15/29466/16885.png/status

**Comment by Spiekerooger** [comment]
I can confirm this problem, you will also see it in the mod tile stats, e.g. at ysera.osm.org/mod_tile

ModTileCacheDurationDirty is never applied in modern buildups as the planet-import-time is not used but dirtying of tiles, pushing them 20 years back and by that tileVeryOld and not tileOld.

This means that dirty/stale tiles returned in case of overloaded tile renderers are send out to the cdn with a way-too-large expire timeframe.
