### ISSUE TITLE
Slowness on high zoom levels

### ISSUE THREAD

**Issue by frafra** [openstreetmap/mod_tile#471]
Hi,
when I use `renderd_list -a` my server generates 1~2 tiles per second on levels 0-8, and around ~30 per second on level 12.
I use a dedicated server, with a Ryzen 5 3600, 64 GB of RAM, consumer NVMe SSDs, OSM carto (with default indexes and a minor change[1]), full planet, Postgres 17, Docker, renderd served over a UNIX socket, jemalloc as memory allocator. The entire setup available at https://github.com/GISdevio/wikimedia-italia-tiles. 

I have no idea if these are good results or not, but they seem decent to me when generating tiles in a batch. The problem is when I ask for few random tiles on a zoom level that has not been generated previously: it takes ~4 minutes on a level 15. It looks like the metatile is set to 16x16 tiles on Debian Bookworm (renderd v0.6.1). I tried using Debian sid, which uses renderd v0.7.1 and Mapnik 4.x, as well as setting mod_tile to batch mode, changing Postgres settings with no success. The server ~1 GB/s from the storage, but it is still slow, and I am surprised that so much data is read.

Am I doing something wrong? I could get a server twice as fast, but it would still be rather unusable. Would it help to reduce the metatile size to 8x8? Would require recompiling mod_tile? Is there anything else I can do?

Test instance available at http://135.181.223.35:8081/carto/. A couple of renderd workers are rendering all the tiles until level 12 in background.

[1] The change is to render the names in Italian whenever possible. The indexes have been modified accordingly, and I verified that there is no big performance hit compared to the standard OSM carto.

**Comment by pnorman** [comment]
It looks like a problem with the style. You should ask the developers of https://github.com/gravitystorm/openstreetmap-carto/compare/master...osmItalia:openstreetmap-carto:name_it_updated

**Comment by frafra** [comment]
Thank you. Even with the original carto style the performances are awful on high zoom levels. I will open an issue on openstreetmap-carto.

**Comment by frafra** [comment]
I can confirm, this is a problem with the custom style. Thank you!
