### ISSUE TITLE
Compiling with Mapnik master (3.x)

### ISSUE THREAD

**Issue by plepe** [openstreetmap/mod_tile#55]
I'm trying to compile mod_tile for Mapnik 3.x, but compiling fails. I guess it has to do with the change to C++11, but I don't know enough about it to fix the problem myself.
- Current mapnik commit: mapnik/mapnik@37eaae3a51753e037b1969c8a1db5754497148fd
- Current mod_tile commit: 681fbd4eb2e1282537f5e1623ab949f55c68c861

Error Log: https://gist.github.com/plepe/7632178

**Comment by flippmoke** [comment]
With mapnik 3.0.0-rc2 being released and us now on a feature freeze, I think is going to be much easier to have a mod_tile target it!

**Comment by xamanu** [comment]
`mod_tile` works well by now with the recent mapnik version. Closing here.
