### ISSUE TITLE
32-bit instead of 8-bit PNG output

### ISSUE THREAD

**Issue by der-stefan** [openstreetmap/mod_tile#64]
Rendering meta tiles with mod_tile/renderd always made my hillshade look ugly. This results in the 8 bit PNGs, which Mapnik doesn't rasterize nicely. The difference can be seen here:
8-bit: ![png256](https://f.cloud.github.com/assets/3618939/1873522/11e41fc2-78bb-11e3-99e0-c4be3c6d901b.png)
32-bit: ![png](https://f.cloud.github.com/assets/3618939/1873520/0494de4c-78bb-11e3-8c2e-2454a3f441ee.png)

Only two lines have to be changed in src/gen_tile.c:
Substitute both "png256" with "png"

There are two possible ways:
- Introduce option in user config file (/usr/local/etc/renderd.conf) for bit depth
- Improve Mapnik. Imagemagick can produce nice looking 8-bit PNGs for example by "convert -type Palette -quality 90 [...]"

**Comment by timautin** [comment]
Any news here? It would be great to have this option.
Anyway, thanks @der-stefan!

**Comment by woodpeck** [comment]
Side note, Tirex (https://github.com/openstreetmap/Tirex) which can be used as a renderd replacement and works nicely with mod_tile, has a per-style `imagetype` configuration option that lets you create 24-bit PNG or even JPEG tiles.

**Comment by timautin** [comment]
@woodpeck Well I just updated mod_tile's code to make it able to take an OUTPUT_FORMAT parameter for each layer, I'll rather send a pull request than changing my stack. Thanks for the suggestion though!

**Comment by mmd-osm** [comment]
mod_tile looks quite abandoned since about 3, maybe even 4-5 years. There's quite a number of outstanding pull requests with suggested improvements, but even merging those seems to be difficult. Not that it would make a difference that I'm mentioning this, though. Maybe that's something for one of the upcoming hack weekends.

**Comment by timautin** [comment]
Oh, I didn't notice that. What is the replacement? Tirex?

**Comment by woodpeck** [comment]
No, Tirex only replaces the renderd part, not the mod_tile part. (It's a bit confusing because both renderd and mod_tile are in this repository together - however using mod_tile and tirex instead of mod_tile and renderd is perfectly possible.)

**Comment by timautin** [comment]
Yeah that's what I figured looking quickly at Tirex. mod_tile still seems to be the "official" way to go.

**Comment by mmd-osm** [comment]
> I wouldn't be too concerned about lack of maintenance though - renderd/mod_tile are intensively used in OpenStreetMap's production setup so if it works for them

Well, it sort of works. However, given how frequently people complain about slow tile rendering or gray tiles, and we already know that there are issues with inefficient queue manegement (#152), I think it's obvious that this area would benefit quite a lot from some rework. Today, most of the CPU resources for rendering are more or less idle during the night, as an example.
