### ISSUE TITLE
Does "tile_dir" option really work?

### ISSUE THREAD

**Issue by Andrey-VI** [openstreetmap/mod_tile#7]
Hi!
I have no success with the "tile_dir" option. Seems that it doesn't work for me. So I need to put a symlinks in /var/lib/mod_tile directory to specify the desired tiles location. Maybe I missed something? Help me understand.

**Comment by roboguy** [comment]
I was trying to add a memcached  storage backend to one of the styles running on my tile server. I just changed the TILEDIR=memcached:// but this style does not work anymore. Does mod_tile need to be compiled with any specific options to enable memcached/rados ? 

Here is my renderd.conf:

[renderd]
socketname=/var/run/renderd/renderd.sock
num_threads=8
tile_dir=/var/lib/mod_tile
stats_file=/var/run/renderd/renderd.stats

[mapnik]
plugins_dir=/usr/lib/mapnik/input
font_dir=/usr/share/fonts/truetype
font_dir_recurse=1

[default]
URI=/default/
TILEDIR=memcached://
XML=/home/ubuntu/src/map-styles/default/project.xml
TILESIZE=256
;MINZOOM=0
;MAXZOOM=22
;TYPE=png image/png
;ASPECTX=1
;ASPECTY=1
