### ISSUE TITLE
"Command failed with rc=65536"

### ISSUE THREAD

**Issue by Gallenkamp** [openstreetmap/mod_tile#73]
Hi there,

I am currently trying to setup a tile server and have Ubunto 10.04 on my hosted machine. Following the tutorial: http://switch2osm.org/serving-tiles/manually-building-a-tile-server/ I come to a point where I have to install mod_tile. That leads to the following result:

guido@myserver:~/src/mod_tile$ sudo make install-mod_tile
mkdir -p `apxs2 -q LIBEXECDIR`
apxs2 -S LIBEXECDIR=`apxs2 -q LIBEXECDIR` -c -i   -I./includes    -lcurl -lcairo   ./src/mod_tile.c ./src/sys_utils.c ./src/store.c ./src/store_file.c ./src/store        _file_utils.c ./src/store_memcached.c ./src/store_rados.c ./src/store_ro_http_proxy.c ./src/store_ro_composite.c ./src/store_null.c
/usr/share/apr-1.0/build/libtool --silent --mode=compile --tag=disable-static x86_64-linux-gnu-gcc -prefer-pic -DLINUX=2 -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -D_REEN        TRANT -I/usr/include/apr-1.0 -I/usr/include/openssl -I/usr/include/xmltok -pthread     -I/usr/include/apache2  -I/usr/include/apr-1.0   -I/usr/include/apr-1.0  -I        ./includes  -c -o ./src/mod_tile.lo ./src/mod_tile.c && touch ./src/mod_tile.slo
./src/mod_tile.c: In function 'socket_init':
./src/mod_tile.c:142: warning: pointer type mismatch in conditional expression
./src/mod_tile.c: In function 'delay_allowed':
./src/mod_tile.c:712: warning: passing argument 1 of 'apr_strtok' discards qualifiers from pointer target type
/usr/include/apr-1.0/apr_strings.h:229: note: expected 'char _' but argument is of type 'const char *'
/usr/share/apr-1.0/build/libtool --silent --mode=compile --tag=disable-static x86_64-linux-gnu-gcc -prefer-pic -DLINUX=2 -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -D_REEN        TRANT -I/usr/include/apr-1.0 -I/usr/include/openssl -I/usr/include/xmltok -pthread     -I/usr/include/apache2  -I/usr/include/apr-1.0   -I/usr/include/apr-1.0  -I        ./includes  -c -o ./src/sys_utils.lo ./src/sys_utils.c && touch ./src/sys_utils.slo
/usr/share/apr-1.0/build/libtool --silent --mode=compile --tag=disable-static x86_64-linux-gnu-gcc -prefer-pic -DLINUX=2 -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -D_REEN        TRANT -I/usr/include/apr-1.0 -I/usr/include/openssl -I/usr/include/xmltok -pthread     -I/usr/include/apache2  -I/usr/include/apr-1.0   -I/usr/include/apr-1.0  -I        ./includes  -c -o ./src/store.lo ./src/store.c && touch ./src/store.slo
/usr/share/apr-1.0/build/libtool --silent --mode=compile --tag=disable-static x86_64-linux-gnu-gcc -prefer-pic -DLINUX=2 -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -D_REEN        TRANT -I/usr/include/apr-1.0 -I/usr/include/openssl -I/usr/include/xmltok -pthread     -I/usr/include/apache2  -I/usr/include/apr-1.0   -I/usr/include/apr-1.0  -I        ./includes  -c -o ./src/store_file.lo ./src/store_file.c && touch ./src/store_file.slo
/usr/share/apr-1.0/build/libtool --silent --mode=compile --tag=disable-static x86_64-linux-gnu-gcc -prefer-pic -DLINUX=2 -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -D_REEN        TRANT -I/usr/include/apr-1.0 -I/usr/include/openssl -I/usr/include/xmltok -pthread     -I/usr/include/apache2  -I/usr/include/apr-1.0   -I/usr/include/apr-1.0  -I        ./includes  -c -o ./src/store_file_utils.lo ./src/store_file_utils.c && touch ./src/store_file_utils.slo
/usr/share/apr-1.0/build/libtool --silent --mode=compile --tag=disable-static x86_64-linux-gnu-gcc -prefer-pic -DLINUX=2 -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -D_REEN        TRANT -I/usr/include/apr-1.0 -I/usr/include/openssl -I/usr/include/xmltok -pthread     -I/usr/include/apache2  -I/usr/include/apr-1.0   -I/usr/include/apr-1.0  -I        ./includes  -c -o ./src/store_memcached.lo ./src/store_memcached.c && touch ./src/store_memcached.slo
./src/store_memcached.c: In function 'init_storage_memcached':
./src/store_memcached.c:233: error: 'STORE_LOGLVL_ERR' undeclared (first use in this function)
./src/store_memcached.c:233: error: (Each undeclared identifier is reported only once
./src/store_memcached.c:233: error: for each function it appears in.)
apxs:Error: Command failed with rc=65536
.
make: *_\* [install-mod_tile] Error 1

I cant tell if its really a mod_tile issue or not, but I am stuck here :(
Any help would be much appreciated!

Guido

**Comment by narcissic** [comment]
Have you by any chance resolved this issue?
I got the same error and I'm stuck here, I think this is the reason why my rendering not working
