### ISSUE TITLE
Support for OpenSuse

### ISSUE THREAD

**Issue by chiranjeevibmse** [openstreetmap/mod_tile#89]
i tried to build the mod_tile as in the http://switch2osm.org/serving-tiles/manually-building-a-tile-server-14-04/

when i run make

the following error is coming

Making all in iniparser3.0b
make[1]: Entering directory `/root/src/mod_tile/iniparser3.0b'
make[1]: Nothing to be done for`all'.
make[1]: Leaving directory `/root/src/mod_tile/iniparser3.0b'
make[1]: Entering directory`/root/src/mod_tile'
depbase=`echo src/gen_tile.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
g++ -DHAVE_CONFIG_H -I. -I./includes  -I/usr/include/freetype2  -I/usr/local/inc                                                                                                             lude -I/usr/local/include/mapnik/agg -I/opt/PostgreSQL/9.3/include -I/usr/includ                                                                                                             e -I/usr/include/freetype2 -I/usr/include/libxml2 -I/usr/include/cairo -I/usr/in                                                                                                             clude/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/pixman-1 -I/usr/incl                                                                                                             ude/libdrm -I/usr/include/libpng12 -I/usr/include  -I/usr/include/cairo -I/usr/i                                                                                                             nclude/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/pixman-1 -I/usr/inc                                                                                                             lude/freetype2 -I/usr/include/libdrm -I/usr/include/libpng12   -DSYSTEM_LIBINIPA                                                                                                             RSER=0   -I/usr/local/include -I/usr/local/include/mapnik/agg -I/opt/PostgreSQL/                                                                                                             9.3/include -I/usr/include -I/usr/include/freetype2 -I/usr/include/libxml2 -I/us                                                                                                             r/include/cairo -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/inc                                                                                                             lude/pixman-1 -I/usr/include/libdrm -I/usr/include/libpng12 -DSHAPE_MEMORY_MAPPE                                                                                                             D_FILE -DBIGINT -DBOOST_REGEX_HAS_ICU -DHAVE_JPEG -DMAPNIK_USE_PROJ4 -DHAVE_PNG                                                                                                              -DHAVE_TIFF -DLINUX -DMAPNIK_THREADSAFE -DBOOST_SPIRIT_NO_PREDEFINED_TERMINALS=1                                                                                                              -DBOOST_PHOENIX_NO_PREDEFINED_TERMINALS=1 -DBOOST_SPIRIT_USE_PHOENIX_V3=1 -DNDE                                                                                                             BUG -DHAVE_CAIRO -DGRID_RENDERER -DHAVE_LIBXML2 -std=c++11 -Wall -Wsign-compare                                                                                                              -pthread -ftemplate-depth-300 -Wno-pragmas -O3 -MT src/gen_tile.o -MD -MP -MF $d                                                                                                             epbase.Tpo -c -o src/gen_tile.o src/gen_tile.cpp &&\
mv -f $depbase.Tpo $depbase.Po
src/gen_tile.cpp: In function ‘void parameterize_map_max_connections(mapnik::Map                                                                                                             &, int)’:
src/gen_tile.cpp:180:35: warning: comparison between signed and unsigned integer                                                                                                              expressions [-Wsign-compare]
     for (i = 0; i < m.layer_count(); i++) {
                                   ^
src/gen_tile.cpp:181:22: error: ‘class mapnik::Map’ has no member named ‘getLaye                                                                                                             r’
         layer& l = m.getLayer(i);
                      ^
src/gen_tile.cpp:182:43: error: invalid use of incomplete type ‘class mapnik::da                                                                                                             tasource’
         parameters params = l.datasource()->params();
                                           ^
In file included from src/gen_tile.cpp:1:0:
/usr/local/include/mapnik/layer.hpp:37:7: error: forward declaration of ‘class m                                                                                                             apnik::datasource’
 class datasource;
       ^
src/gen_tile.cpp:188:9: error: ‘shared_ptr’ is not a member of ‘boost’
         boost::shared_ptr<datasource> ds = datasource_cache::instance().create(                                                                                                             params);
         ^
src/gen_tile.cpp:188:9: note: suggested alternative:
In file included from /usr/include/c++/4.8/bits/shared_ptr.h:52:0,
                 from /usr/include/c++/4.8/memory:82,
                 from /usr/local/include/mapnik/layer.hpp:32,
                 from src/gen_tile.cpp:1:
/usr/include/c++/4.8/bits/shared_ptr_base.h:261:11: note:   ‘std::shared_ptr’
     class shared_ptr;
           ^
src/gen_tile.cpp:188:37: error: expected primary-expression before ‘>’ token
         boost::shared_ptr<datasource> ds = datasource_cache::instance().create(                                                                                                             params);
                                     ^
src/gen_tile.cpp:188:39: error: ‘ds’ was not declared in this scope
         boost::shared_ptr<datasource> ds = datasource_cache::instance().create(                                                                                                             params);
                                       ^
src/gen_tile.cpp: In function ‘protoCmd render(xmlmapconfig_, int, int, int, cha                                                                                                             r_, metaTile&)’:
src/gen_tile.cpp:259:23: warning: comparison between signed and unsigned integer                                                                                                              expressions [-Wsign-compare]
     for (yy = 0; yy < render_size_ty; yy++) {
                       ^
src/gen_tile.cpp:260:27: warning: comparison between signed and unsigned integer                                                                                                              expressions [-Wsign-compare]
         for (xx = 0; xx < render_size_tx; xx++) {
                           ^
make[1]: **\* [src/gen_tile.o] Error 1
make[1]: Leaving directory `/root/src/mod_tile'
make: **\* [all-recursive] Error 1

**Comment by xamanu** [comment]
Can anybody try to compile this on a recent OpenSuse version? I would be curious to know if it works or if there are any problems. Thank you.

**Comment by xamanu** [comment]
We have been adding back support for Fedora #232 and CentOS #230, by:

* adding a CI pipeline (based on Github Actions) for each of the distributions
* adding simple step by step documentation on how to compile the sofwtare

To officially support OpenSuse, we should achieve similar things.
