### ISSUE TITLE
Memcached Rados configuration error 

### ISSUE THREAD

**Issue by roboguy** [openstreetmap/mod_tile#95]
I was trying to add a memcached  storage backend to one of the styles running on my tile server. I just changed the TILEDIR=memcached:// but this style does not work anymore. Does mod_tile need to be compiled with any specific options to enable memcached/rados ? 
#7

Here is my renderd.conf:

[renderd]
socketname=/var/run/renderd/renderd.sock
num_threads=8
tile_dir=/var/lib/mod_tile
stats_file=/var/run/renderd/renderd.stats

[mapnik]
plugins_dir=/usr/lib/mapnik/input
font_dir=/usr/share/fonts/truetype
font_dir_recurse=1

[default]
URI=/default/
TILEDIR=memcached://
XML=/home/ubuntu/src/map-styles/default/project.xml
TILESIZE=256
;MINZOOM=0
;MAXZOOM=22
;TYPE=png image/png
;ASPECTX=1
;ASPECTY=1

**Comment by wbaizer** [comment]
Hey @roboguy, did you ever get this figured out?

I cannot figure out why I'm getting the error
`renderd[10095]: Loading parameterization function for debug: init_storage_backend: initialising memcached storage backend at: memcached://
ERROR: init_storage_memcached: Support for memcached has not been compiled into this program
`
I have my Tile_dir set up like yours.

**Comment by apmon** [comment]
I haven't looked at the mod_tile/renderd source code in quite a while. So I don't know for sure if this code still works or not. But from a brief look at the current source code, it looks like what triggers if memcached support is compiled in is the preprocessor directive "HAVE_LIBMEMCACHED". So my guess is that the configure script looks for if the development header/library of libmemcached are installed and if yes, its support should be compiled in.

Do you know if you do have the development files for libmemcached installed?
