### ISSUE TITLE
Style attribution doesn't showing

### ISSUE THREAD

**Issue by adam21** [openstreetmap/mod_tile#97]
Hello everyone,

I uncommented the following line in the renderd.conf file:
ATTRIBUTION=&copy;<a href=\"http://www.openstreetmap.org/\">OpenStreetMap</a> and <a href=\"http://wiki.openstreetmap.org/wiki/Contributors\">contributors</a>, <a href=\"http://opendatacommons.org/licenses/odbl/\">ODbL</a>

But after restarting the server and tested the map, the attribution does not appear
Have you any idea? thank you for your help

**Comment by xamanu** [comment]
Please check in your website that shows the map layers.
